// A2 VOCABULARY
const VOCAB_A2 = {
"Trabajo 💼":[
{es:"el jefe",de:"der Chef",article:"der",emoji:"👔",pron:"[ʃɛf]"},
{es:"el colega",de:"der Kollege",article:"der",emoji:"🤝",pron:"[kɔˈleːɡə]"},
{es:"la reunión",de:"die Besprechung",article:"die",emoji:"📋",pron:"[bəˈʃprɛçʊŋ]"},
{es:"el sueldo",de:"das Gehalt",article:"das",emoji:"💰",pron:"[ɡəˈhalt]"},
{es:"las vacaciones",de:"der Urlaub",article:"der",emoji:"🏖️",pron:"[ˈuːɐ̯laʊp]"},
{es:"la solicitud",de:"die Bewerbung",article:"die",emoji:"📄",pron:"[bəˈvɛrbʊŋ]"},
{es:"la experiencia",de:"die Erfahrung",article:"die",emoji:"⭐",pron:"[ɛɐ̯ˈfaːrʊŋ]"},
{es:"el contrato",de:"der Vertrag",article:"der",emoji:"📝",pron:"[fɛɐ̯ˈtraːk]"},
{es:"la fábrica",de:"die Fabrik",article:"die",emoji:"🏭",pron:"[faˈbriːk]"},
{es:"la cadena de montaje",de:"das Fließband",article:"das",emoji:"⚙️",pron:"[ˈfliːsbant]"},
{es:"la empresa",de:"die Firma",article:"die",emoji:"🏢",pron:"[ˈfɪrma]"},
{es:"el empleado",de:"der Angestellte",article:"der",emoji:"🧑‍💼",pron:"[ˈanɡəʃtɛltə]"},
{es:"el turno",de:"die Schicht",article:"die",emoji:"🔄",pron:"[ʃɪçt]"},
{es:"despedir",de:"kündigen",article:"",emoji:"❌",pron:"[ˈkʏndɪɡn̩]"},
{es:"ganar (dinero)",de:"verdienen",article:"",emoji:"💶",pron:"[fɛɐ̯ˈdiːnən]"},
],
"Vivienda 🏠":[
{es:"la mudanza",de:"der Umzug",article:"der",emoji:"📦",pron:"[ˈʊmtsuːk]"},
{es:"el mueble",de:"das Möbel",article:"das",emoji:"🪑",pron:"[ˈmøːbl̩]"},
{es:"la cómoda",de:"die Kommode",article:"die",emoji:"🗄️",pron:"[kɔˈmoːdə]"},
{es:"la estantería",de:"das Regal",article:"das",emoji:"📚",pron:"[reˈɡaːl]"},
{es:"el armario",de:"der Schrank",article:"der",emoji:"🚪",pron:"[ʃraŋk]"},
{es:"la alfombra",de:"der Teppich",article:"der",emoji:"🟫",pron:"[ˈtɛpɪç]"},
{es:"la cortina",de:"der Vorhang",article:"der",emoji:"🪟",pron:"[ˈfoːɐ̯haŋ]"},
{es:"el alquiler",de:"die Miete",article:"die",emoji:"💶",pron:"[ˈmiːtə]"},
{es:"el inquilino",de:"der Mieter",article:"der",emoji:"🔑",pron:"[ˈmiːtɐ]"},
{es:"el propietario",de:"der Vermieter",article:"der",emoji:"🏠",pron:"[fɛɐ̯ˈmiːtɐ]"},
{es:"colgar",de:"hängen",article:"",emoji:"🖼️",pron:"[ˈhɛŋən]"},
{es:"colocar (de pie)",de:"stellen",article:"",emoji:"🧍",pron:"[ˈʃtɛlən]"},
{es:"poner/acostar",de:"legen",article:"",emoji:"📐",pron:"[ˈleːɡn̩]"},
{es:"estar colgado",de:"hängen",article:"",emoji:"🖼️",pron:"[ˈhɛŋən]"},
{es:"estar de pie",de:"stehen",article:"",emoji:"🧍",pron:"[ˈʃteːən]"},
],
"Turismo 🗺️":[
{es:"el viaje",de:"die Reise",article:"die",emoji:"✈️",pron:"[ˈraɪzə]"},
{es:"el alojamiento",de:"die Unterkunft",article:"die",emoji:"🏨",pron:"[ˈʊntɐkʊnft]"},
{es:"la visita guiada",de:"die Führung",article:"die",emoji:"🎙️",pron:"[ˈfyːrʊŋ]"},
{es:"el monumento",de:"die Sehenswürdigkeit",article:"die",emoji:"🏛️",pron:""},
{es:"la catedral",de:"der Dom",article:"der",emoji:"⛪",pron:"[doːm]"},
{es:"el paisaje",de:"die Landschaft",article:"die",emoji:"🏞️",pron:"[ˈlantʃaft]"},
{es:"la montaña",de:"der Berg",article:"der",emoji:"⛰️",pron:"[bɛrk]"},
{es:"el lago",de:"der See",article:"der",emoji:"🏊",pron:"[zeː]"},
{es:"el mar",de:"das Meer",article:"das",emoji:"🌊",pron:"[meːɐ̯]"},
{es:"la playa",de:"der Strand",article:"der",emoji:"🏖️",pron:"[ʃtrant]"},
{es:"el bosque",de:"der Wald",article:"der",emoji:"🌲",pron:"[valt]"},
{es:"el sendero",de:"der Weg",article:"der",emoji:"🥾",pron:"[veːk]"},
{es:"hacer senderismo",de:"wandern",article:"",emoji:"🥾",pron:"[ˈvandɐn]"},
{es:"reservar",de:"reservieren",article:"",emoji:"📞",pron:"[rezɛrˈviːrən]"},
{es:"la pensión completa",de:"die Vollpension",article:"die",emoji:"🍽️",pron:""},
],
"Compras 🛒":[
{es:"la oferta",de:"das Angebot",article:"das",emoji:"🏷️",pron:"[ˈanɡəboːt]"},
{es:"la caja",de:"die Kasse",article:"die",emoji:"🧾",pron:"[ˈkasə]"},
{es:"el paquete",de:"die Packung",article:"die",emoji:"📦",pron:"[ˈpakʊŋ]"},
{es:"la lata",de:"die Dose",article:"die",emoji:"🥫",pron:"[ˈdoːzə]"},
{es:"la bolsa",de:"die Tüte",article:"die",emoji:"🛍️",pron:"[ˈtyːtə]"},
{es:"el carrito",de:"der Einkaufswagen",article:"der",emoji:"🛒",pron:""},
{es:"pesar",de:"wiegen",article:"",emoji:"⚖️",pron:"[ˈviːɡn̩]"},
{es:"la pieza",de:"das Stück",article:"das",emoji:"🧩",pron:"[ʃtʏk]"},
{es:"el caramelo",de:"das Bonbon",article:"das",emoji:"🍬",pron:"[bɔŋˈbɔŋ]"},
{es:"las cerezas",de:"die Kirschen",article:"die",emoji:"🍒",pron:"[ˈkɪrʃn̩]"},
{es:"el pepino",de:"die Gurke",article:"die",emoji:"🥒",pron:"[ˈɡʊrkə]"},
{es:"el ajo",de:"der Knoblauch",article:"der",emoji:"🧄",pron:"[ˈknoːblaʊx]"},
{es:"la harina",de:"das Mehl",article:"das",emoji:"🌾",pron:"[meːl]"},
{es:"la mermelada",de:"die Marmelade",article:"die",emoji:"🍯",pron:"[marməˈlaːdə]"},
{es:"el atún",de:"der Thunfisch",article:"der",emoji:"🐟",pron:"[ˈtuːnfɪʃ]"},
],
"Deportes 🏃":[
{es:"correr",de:"joggen",article:"",emoji:"🏃",pron:"[ˈdʒɔɡn̩]"},
{es:"nadar",de:"schwimmen",article:"",emoji:"🏊",pron:"[ˈʃvɪmən]"},
{es:"el baloncesto",de:"der Basketball",article:"der",emoji:"🏀",pron:""},
{es:"el voleibol",de:"der Volleyball",article:"der",emoji:"🏐",pron:""},
{es:"el balonmano",de:"der Handball",article:"der",emoji:"🤾",pron:""},
{es:"el yoga",de:"das Yoga",article:"das",emoji:"🧘",pron:"[ˈjoːɡa]"},
{es:"el gimnasio",de:"das Fitnessstudio",article:"das",emoji:"🏋️",pron:""},
{es:"el entrenador",de:"der Trainer",article:"der",emoji:"🧑‍🏫",pron:"[ˈtreːnɐ]"},
{es:"el equipo",de:"die Mannschaft",article:"die",emoji:"👥",pron:"[ˈmanʃaft]"},
{es:"ganar",de:"gewinnen",article:"",emoji:"🏆",pron:"[ɡəˈvɪnən]"},
{es:"perder",de:"verlieren",article:"",emoji:"😞",pron:"[fɛɐ̯ˈliːrən]"},
{es:"entrenar",de:"trainieren",article:"",emoji:"💪",pron:"[treˈniːrən]"},
{es:"la competición",de:"der Wettkampf",article:"der",emoji:"🥇",pron:"[ˈvɛtkampf]"},
{es:"el excursionismo",de:"das Wandern",article:"das",emoji:"🥾",pron:"[ˈvandɐn]"},
{es:"remar",de:"rudern",article:"",emoji:"🚣",pron:"[ˈruːdɐn]"},
],
"Salud 🏥":[
{es:"el accidente",de:"der Unfall",article:"der",emoji:"🚑",pron:"[ˈʊnfal]"},
{es:"la ambulancia",de:"der Krankenwagen",article:"der",emoji:"🚑",pron:""},
{es:"el hospital",de:"das Krankenhaus",article:"das",emoji:"🏥",pron:"[ˈkraŋkn̩haʊs]"},
{es:"la urgencia",de:"die Notaufnahme",article:"die",emoji:"🚨",pron:""},
{es:"la operación",de:"die Operation",article:"die",emoji:"🔪",pron:"[ˌopeʁaˈt͡si̯oːn]"},
{es:"la venda",de:"der Verband",article:"der",emoji:"🩹",pron:"[fɛɐ̯ˈbant]"},
{es:"la muleta",de:"die Krücke",article:"die",emoji:"🦯",pron:"[ˈkrʏkə]"},
{es:"sangrar",de:"bluten",article:"",emoji:"🩸",pron:"[ˈbluːtn̩]"},
{es:"el dolor",de:"der Schmerz",article:"der",emoji:"😣",pron:"[ʃmɛrts]"},
{es:"el corazón",de:"das Herz",article:"das",emoji:"❤️",pron:"[hɛrts]"},
{es:"el estómago",de:"der Magen",article:"der",emoji:"🤢",pron:"[ˈmaːɡn̩]"},
{es:"la fiebre",de:"das Fieber",article:"das",emoji:"🤒",pron:"[ˈfiːbɐ]"},
{es:"el resfriado",de:"die Erkältung",article:"die",emoji:"🤧",pron:"[ɛɐ̯ˈkɛltʊŋ]"},
{es:"la receta",de:"das Rezept",article:"das",emoji:"📋",pron:"[reˈtsɛpt]"},
{es:"el seguro médico",de:"die Krankenversicherung",article:"die",emoji:"🏥",pron:""},
],
"Cultura 🎭":[
{es:"el evento",de:"die Veranstaltung",article:"die",emoji:"🎪",pron:"[fɛɐ̯ˈanʃtaltʊŋ]"},
{es:"el concierto",de:"das Konzert",article:"das",emoji:"🎵",pron:"[kɔnˈtsɛrt]"},
{es:"el festival",de:"das Festival",article:"das",emoji:"🎉",pron:"[ˈfɛstɪval]"},
{es:"el teatro",de:"das Theater",article:"das",emoji:"🎭",pron:"[teˈaːtɐ]"},
{es:"el museo",de:"das Museum",article:"das",emoji:"🏛️",pron:"[muˈzeːʊm]"},
{es:"la entrada",de:"die Eintrittskarte",article:"die",emoji:"🎫",pron:""},
{es:"el cine",de:"das Kino",article:"das",emoji:"🎬",pron:"[ˈkiːno]"},
{es:"la exposición",de:"die Ausstellung",article:"die",emoji:"🖼️",pron:"[ˈaʊsʃtɛlʊŋ]"},
{es:"abierto",de:"geöffnet",article:"",emoji:"🟢",pron:"[ɡəˈʔœfnət]"},
{es:"cerrado",de:"geschlossen",article:"",emoji:"🔴",pron:"[ɡəˈʃlɔsn̩]"},
{es:"la cervecería",de:"das Brauhaus",article:"das",emoji:"🍺",pron:"[ˈbraʊhaʊs]"},
{es:"el espectáculo",de:"die Vorstellung",article:"die",emoji:"🎪",pron:"[ˈfoːɐ̯ʃtɛlʊŋ]"},
],
"Restaurante 🍽️":[
{es:"el plato",de:"der Teller",article:"der",emoji:"🍽️",pron:"[ˈtɛlɐ]"},
{es:"el vaso",de:"das Glas",article:"das",emoji:"🥛",pron:"[ɡlaːs]"},
{es:"el cuchillo",de:"das Messer",article:"das",emoji:"🔪",pron:"[ˈmɛsɐ]"},
{es:"el tenedor",de:"die Gabel",article:"die",emoji:"🍴",pron:"[ˈɡaːbl̩]"},
{es:"la cuchara",de:"der Löffel",article:"der",emoji:"🥄",pron:"[ˈlœfl̩]"},
{es:"la servilleta",de:"die Serviette",article:"die",emoji:"🧻",pron:"[zɛrˈvi̯ɛtə]"},
{es:"el salero",de:"der Salzstreuer",article:"der",emoji:"🧂",pron:""},
{es:"la propina",de:"das Trinkgeld",article:"das",emoji:"💵",pron:"[ˈtrɪŋkɡɛlt]"},
{es:"la carta de vinos",de:"die Weinkarte",article:"die",emoji:"🍷",pron:""},
{es:"el entrante",de:"die Vorspeise",article:"die",emoji:"🥗",pron:"[ˈfoːɐ̯ʃpaɪzə]"},
{es:"el plato principal",de:"das Hauptgericht",article:"das",emoji:"🥩",pron:"[ˈhaʊptɡərɪçt]"},
{es:"el postre",de:"der Nachtisch",article:"der",emoji:"🍰",pron:"[ˈnaːxtɪʃ]"},
{es:"pedir",de:"bestellen",article:"",emoji:"📝",pron:"[bəˈʃtɛlən]"},
{es:"reservar",de:"reservieren",article:"",emoji:"📞",pron:"[rezɛrˈviːrən]"},
{es:"probar",de:"probieren",article:"",emoji:"😋",pron:"[proˈbiːrən]"},
],
"Personalidad 😊":[
{es:"amable",de:"freundlich",article:"",emoji:"😊",pron:"[ˈfrɔʏntlɪç]"},
{es:"antipático",de:"unfreundlich",article:"",emoji:"😠",pron:"[ˈʊnfrɔʏntlɪç]"},
{es:"gracioso",de:"lustig",article:"",emoji:"😂",pron:"[ˈlʊstɪç]"},
{es:"serio",de:"ernst",article:"",emoji:"😐",pron:"[ɛrnst]"},
{es:"tímido",de:"schüchtern",article:"",emoji:"😳",pron:"[ˈʃʏçtɐn]"},
{es:"abierto",de:"offen",article:"",emoji:"🤗",pron:"[ˈɔfn̩]"},
{es:"perezoso",de:"faul",article:"",emoji:"😴",pron:"[faʊl]"},
{es:"trabajador",de:"fleißig",article:"",emoji:"💪",pron:"[ˈflaɪsɪç]"},
{es:"nervioso",de:"nervös",article:"",emoji:"😰",pron:"[nɛrˈvøːs]"},
{es:"celoso",de:"eifersüchtig",article:"",emoji:"😤",pron:"[ˈaɪfɐzʏçtɪç]"},
{es:"orgulloso",de:"stolz",article:"",emoji:"🦚",pron:"[ʃtɔlts]"},
{es:"valiente",de:"mutig",article:"",emoji:"🦁",pron:"[ˈmuːtɪç]"},
{es:"sincero",de:"ehrlich",article:"",emoji:"🤝",pron:"[ˈeːɐ̯lɪç]"},
{es:"paciente",de:"geduldig",article:"",emoji:"🧘",pron:"[ɡəˈdʊldɪç]"},
{es:"curioso",de:"neugierig",article:"",emoji:"🔍",pron:"[ˈnɔʏɡiːrɪç]"},
],
"Cuerpo y cuidado 🧴":[
{es:"la espalda",de:"der Rücken",article:"der",emoji:"🔙",pron:"[ˈrʏkn̩]"},
{es:"el cuello",de:"der Hals",article:"der",emoji:"🦒",pron:"[hals]"},
{es:"el hombro",de:"die Schulter",article:"die",emoji:"💪",pron:"[ˈʃʊltɐ]"},
{es:"la piel",de:"die Haut",article:"die",emoji:"🤚",pron:"[haʊt]"},
{es:"el hueso",de:"der Knochen",article:"der",emoji:"🦴",pron:"[ˈknɔxn̩]"},
{es:"la sangre",de:"das Blut",article:"das",emoji:"🩸",pron:"[bluːt]"},
{es:"el cepillo de dientes",de:"die Zahnbürste",article:"die",emoji:"🪥",pron:"[ˈtsaːnbʏrstə]"},
{es:"el jabón",de:"die Seife",article:"die",emoji:"🧼",pron:"[ˈzaɪfə]"},
{es:"la toalla",de:"das Handtuch",article:"das",emoji:"🛁",pron:"[ˈhanttuːx]"},
{es:"el peine",de:"der Kamm",article:"der",emoji:"💇",pron:"[kam]"},
{es:"la crema",de:"die Creme",article:"die",emoji:"🧴",pron:"[kreːm]"},
{es:"el espejo",de:"der Spiegel",article:"der",emoji:"🪞",pron:"[ˈʃpiːɡl̩]"},
{es:"ducharse",de:"duschen",article:"",emoji:"🚿",pron:"[ˈdʊʃn̩]"},
{es:"bañarse",de:"baden",article:"",emoji:"🛀",pron:"[ˈbaːdn̩]"},
{es:"afeitarse",de:"sich rasieren",article:"",emoji:"🪒",pron:"[zɪç raˈziːrən]"},
],
"Ropa ampliada 👗":[
{es:"el anillo",de:"der Ring",article:"der",emoji:"💍",pron:"[rɪŋ]"},
{es:"el bolso",de:"die Handtasche",article:"die",emoji:"👜",pron:"[ˈhanttaʃə]"},
{es:"el guante",de:"der Handschuh",article:"der",emoji:"🧤",pron:"[ˈhantʃuː]"},
{es:"el botón",de:"der Knopf",article:"der",emoji:"🔘",pron:"[knɔpf]"},
{es:"el paraguas",de:"der Schirm",article:"der",emoji:"☂️",pron:"[ʃɪrm]"},
{es:"el traje de baño",de:"die Badehose",article:"die",emoji:"🩳",pron:"[ˈbaːdəhoːzə]"},
{es:"la lana",de:"die Wolle",article:"die",emoji:"🧶",pron:"[ˈvɔlə]"},
{es:"el algodón",de:"die Baumwolle",article:"die",emoji:"☁️",pron:"[ˈbaʊmvɔlə]"},
{es:"estrecho",de:"eng",article:"",emoji:"📏",pron:"[ɛŋ]"},
{es:"ancho",de:"weit",article:"",emoji:"↔️",pron:"[vaɪt]"},
{es:"probarse",de:"anprobieren",article:"",emoji:"👔",pron:"[ˈanproˌbiːrən]"},
{es:"vestirse",de:"sich anziehen",article:"",emoji:"👕",pron:""},
{es:"desvestirse",de:"sich ausziehen",article:"",emoji:"👚",pron:""},
{es:"la talla",de:"die Größe",article:"die",emoji:"📐",pron:"[ˈɡrøːsə]"},
{es:"la moda",de:"die Mode",article:"die",emoji:"✨",pron:"[ˈmoːdə]"},
],
"Casa ampliada 🏗️":[
{es:"el sótano",de:"der Keller",article:"der",emoji:"⬇️",pron:"[ˈkɛlɐ]"},
{es:"el tejado",de:"das Dach",article:"das",emoji:"🏠",pron:"[dax]"},
{es:"la pared",de:"die Wand",article:"die",emoji:"🧱",pron:"[vant]"},
{es:"el suelo",de:"der Boden",article:"der",emoji:"⬛",pron:"[ˈboːdn̩]"},
{es:"el techo",de:"die Decke",article:"die",emoji:"⬜",pron:"[ˈdɛkə]"},
{es:"el cojín",de:"das Kissen",article:"das",emoji:"🛋️",pron:"[ˈkɪsn̩]"},
{es:"la imagen/cuadro",de:"das Bild",article:"das",emoji:"🖼️",pron:"[bɪlt]"},
{es:"el sillón",de:"der Sessel",article:"der",emoji:"🪑",pron:"[ˈzɛsl̩]"},
{es:"la televisión",de:"der Fernseher",article:"der",emoji:"📺",pron:"[ˈfɛrnzeːɐ]"},
{es:"la luz",de:"das Licht",article:"das",emoji:"💡",pron:"[lɪçt]"},
{es:"la electricidad",de:"der Strom",article:"der",emoji:"⚡",pron:"[ʃtroːm]"},
{es:"construir",de:"bauen",article:"",emoji:"🏗️",pron:"[ˈbaʊən]"},
{es:"moderno",de:"modern",article:"",emoji:"✨",pron:"[moˈdɛrn]"},
{es:"acogedor",de:"gemütlich",article:"",emoji:"🏡",pron:"[ɡəˈmyːtlɪç]"},
{es:"oscuro",de:"dunkel",article:"",emoji:"🌑",pron:"[ˈdʊŋkl̩]"},
{es:"claro/luminoso",de:"hell",article:"",emoji:"☀️",pron:"[hɛl]"},
{es:"vacío",de:"leer",article:"",emoji:"📦",pron:"[leːɐ̯]"},
],
"Correos y documentos 📮":[
{es:"el pasaporte",de:"der Pass",article:"der",emoji:"🛂",pron:"[pas]"},
{es:"el permiso de conducir",de:"der Führerschein",article:"der",emoji:"🪪",pron:"[ˈfyːrɐʃaɪn]"},
{es:"el documento",de:"das Dokument",article:"das",emoji:"📄",pron:"[dokuˈmɛnt]"},
{es:"el sobre",de:"der Umschlag",article:"der",emoji:"✉️",pron:"[ˈʊmʃlaːk]"},
{es:"la postal",de:"die Postkarte",article:"die",emoji:"🏖️",pron:"[ˈpɔstkartə]"},
{es:"el paquetito",de:"das Päckchen",article:"das",emoji:"📦",pron:"[ˈpɛkçən]"},
{es:"la denuncia",de:"die Anzeige",article:"die",emoji:"📋",pron:"[ˈantsaɪɡə]"},
{es:"robar",de:"stehlen",article:"",emoji:"🦹",pron:"[ˈʃteːlən]"},
{es:"el ladrón",de:"der Dieb",article:"der",emoji:"🦹",pron:"[diːp]"},
{es:"el accidente",de:"der Unfall",article:"der",emoji:"💥",pron:"[ˈʊnfal]"},
{es:"el permiso de residencia",de:"die Aufenthaltserlaubnis",article:"die",emoji:"🏛️",pron:""},
{es:"el certificado",de:"die Bescheinigung",article:"die",emoji:"📜",pron:"[bəˈʃaɪnɪɡʊŋ]"},
],
"Naturaleza 🌿":[
{es:"el campo/granja",de:"der Bauernhof",article:"der",emoji:"🌾",pron:"[ˈbaʊɐnhoːf]"},
{es:"la isla",de:"die Insel",article:"die",emoji:"🏝️",pron:"[ˈɪnzl̩]"},
{es:"el río",de:"der Fluss",article:"der",emoji:"🏞️",pron:"[flʊs]"},
{es:"la colina",de:"der Hügel",article:"der",emoji:"⛰️",pron:"[ˈhyːɡl̩]"},
{es:"el prado",de:"die Wiese",article:"die",emoji:"🌱",pron:"[ˈviːzə]"},
{es:"la tierra",de:"die Erde",article:"die",emoji:"🌍",pron:"[ˈeːɐ̯də]"},
{es:"la piedra",de:"der Stein",article:"der",emoji:"🪨",pron:"[ʃtaɪn]"},
{es:"la hoja",de:"das Blatt",article:"das",emoji:"🍃",pron:"[blat]"},
{es:"la hierba",de:"das Gras",article:"das",emoji:"🌿",pron:"[ɡraːs]"},
{es:"el aire",de:"die Luft",article:"die",emoji:"💨",pron:"[lʊft]"},
{es:"el fuego",de:"das Feuer",article:"das",emoji:"🔥",pron:"[ˈfɔʏɐ]"},
{es:"la luna",de:"der Mond",article:"der",emoji:"🌙",pron:"[moːnt]"},
{es:"la estrella",de:"der Stern",article:"der",emoji:"⭐",pron:"[ʃtɛrn]"},
],
"Transporte A2 🚄":[
{es:"el semáforo",de:"die Ampel",article:"die",emoji:"🚦",pron:"[ˈampl̩]"},
{es:"el atasco",de:"der Stau",article:"der",emoji:"🚗",pron:"[ʃtaʊ]"},
{es:"la gasolina",de:"das Benzin",article:"das",emoji:"⛽",pron:"[bɛnˈtsiːn]"},
{es:"el carné de conducir",de:"der Führerschein",article:"der",emoji:"🪪",pron:"[ˈfyːrɐʃaɪn]"},
{es:"aparcar",de:"parken",article:"",emoji:"🅿️",pron:"[ˈparkn̩]"},
{es:"el accidente",de:"der Unfall",article:"der",emoji:"💥",pron:"[ˈʊnfal]"},
{es:"el neumático",de:"der Reifen",article:"der",emoji:"🛞",pron:"[ˈraɪfn̩]"},
{es:"la autopista",de:"die Autobahn",article:"die",emoji:"🛣️",pron:"[ˈaʊtobaːn]"},
{es:"la salida",de:"die Ausfahrt",article:"die",emoji:"🚪",pron:"[ˈaʊsfaːɐ̯t]"},
{es:"la velocidad",de:"die Geschwindigkeit",article:"die",emoji:"💨",pron:""},
{es:"el tranvía",de:"die Straßenbahn",article:"die",emoji:"🚃",pron:"[ˈʃtraːsn̩baːn]"},
{es:"la conexión/enlace",de:"der Anschluss",article:"der",emoji:"🔗",pron:"[ˈanʃlʊs]"},
],
"Aprendizaje 📚":[
{es:"el curso",de:"der Kurs",article:"der",emoji:"📚",pron:"[kʊrs]"},
{es:"la formación",de:"die Ausbildung",article:"die",emoji:"🎓",pron:"[ˈaʊsbɪldʊŋ]"},
{es:"la carrera/estudios",de:"das Studium",article:"das",emoji:"🎓",pron:"[ˈʃtuːdiʊm]"},
{es:"el certificado",de:"das Zeugnis",article:"das",emoji:"📜",pron:"[ˈtsɔʏɡnɪs]"},
{es:"la nota/calificación",de:"die Note",article:"die",emoji:"📝",pron:"[ˈnoːtə]"},
{es:"aprobar",de:"bestehen",article:"",emoji:"✅",pron:"[bəˈʃteːən]"},
{es:"suspender",de:"durchfallen",article:"",emoji:"❌",pron:"[ˈdʊrçfalən]"},
{es:"la asignatura",de:"das Fach",article:"das",emoji:"📖",pron:"[fax]"},
{es:"la presentación",de:"die Präsentation",article:"die",emoji:"📊",pron:"[prɛzɛntaˈt͡si̯oːn]"},
{es:"el conocimiento",de:"die Kenntnis",article:"die",emoji:"🧠",pron:"[ˈkɛntnɪs]"},
{es:"mejorar",de:"verbessern",article:"",emoji:"📈",pron:"[fɛɐ̯ˈbɛsɐn]"},
{es:"practicar",de:"üben",article:"",emoji:"🔄",pron:"[ˈyːbn̩]"},
],
"Sentimientos 💭":[
{es:"alegrarse",de:"sich freuen",article:"",emoji:"😊",pron:"[zɪç ˈfrɔʏən]"},
{es:"enfadarse",de:"sich ärgern",article:"",emoji:"😠",pron:"[zɪç ˈɛrɡɐn]"},
{es:"tener miedo",de:"Angst haben",article:"",emoji:"😨",pron:"[aŋst haːbn̩]"},
{es:"sorprenderse",de:"sich wundern",article:"",emoji:"😲",pron:"[zɪç ˈvʊndɐn]"},
{es:"aburrirse",de:"sich langweilen",article:"",emoji:"😑",pron:"[zɪç ˈlaŋvaɪlən]"},
{es:"preocuparse",de:"sich Sorgen machen",article:"",emoji:"😟",pron:""},
{es:"echar de menos",de:"vermissen",article:"",emoji:"💔",pron:"[fɛɐ̯ˈmɪsn̩]"},
{es:"reír",de:"lachen",article:"",emoji:"😂",pron:"[ˈlaxn̩]"},
{es:"llorar",de:"weinen",article:"",emoji:"😢",pron:"[ˈvaɪnən]"},
{es:"soñar",de:"träumen",article:"",emoji:"💭",pron:"[ˈtrɔʏmən]"},
{es:"discutir",de:"streiten",article:"",emoji:"🗣️",pron:"[ˈʃtraɪtn̩]"},
{es:"disculparse",de:"sich entschuldigen",article:"",emoji:"🙏",pron:"[zɪç ɛntˈʃʊldɪɡn̩]"},
],
"Verbos A2 🔧":[
{es:"intentar",de:"versuchen",article:"",emoji:"🎯",pron:"[fɛɐ̯ˈzuːxn̩]"},
{es:"proponer",de:"vorschlagen",article:"",emoji:"💡",pron:"[ˈfoːɐ̯ʃlaːɡn̩]"},
{es:"decidir",de:"entscheiden",article:"",emoji:"⚖️",pron:"[ɛntˈʃaɪdn̩]"},
{es:"comparar",de:"vergleichen",article:"",emoji:"🔍",pron:"[fɛɐ̯ˈɡlaɪçn̩]"},
{es:"cambiar",de:"ändern",article:"",emoji:"🔄",pron:"[ˈɛndɐn]"},
{es:"mudarse",de:"umziehen",article:"",emoji:"📦",pron:"[ˈʊmtsiːən]"},
{es:"quejarse",de:"sich beschweren",article:"",emoji:"😤",pron:"[zɪç bəˈʃveːrən]"},
{es:"recordar",de:"sich erinnern",article:"",emoji:"🧠",pron:"[zɪç ɛɐ̯ˈɪnɐn]"},
{es:"olvidar",de:"vergessen",article:"",emoji:"🤔",pron:"[fɛɐ̯ˈɡɛsn̩]"},
{es:"participar",de:"teilnehmen",article:"",emoji:"🙋",pron:"[ˈtaɪlneːmən]"},
{es:"devolver",de:"zurückgeben",article:"",emoji:"↩️",pron:"[tsuˈrʏkɡeːbn̩]"},
{es:"explicar",de:"erklären",article:"",emoji:"💬",pron:"[ɛɐ̯ˈklɛːrən]"},
{es:"limpiar",de:"putzen",article:"",emoji:"🧹",pron:"[ˈpʊtsn̩]"},
{es:"reparar",de:"reparieren",article:"",emoji:"🔧",pron:"[repaˈriːrən]"},
{es:"celebrar",de:"feiern",article:"",emoji:"🎉",pron:"[ˈfaɪɐn]"},
],
"Goethe A2 extra 📋":[
{es:"el fan",de:"der Fan",article:"der",emoji:"🎉",pron:"[fɛn]"},
{es:"fantástico",de:"fantastisch",article:"",emoji:"🤩",pron:"[fanˈtastɪʃ]"},
{es:"casi",de:"fast",article:"",emoji:"⏳",pron:"[fast]"},
{es:"la fiesta",de:"das Fest",article:"das",emoji:"🎊",pron:"[fɛst]"},
{es:"húmedo",de:"nass",article:"",emoji:"💧",pron:"[nas]"},
{es:"seco",de:"trocken",article:"",emoji:"☀️",pron:"[ˈtrɔkn̩]"},
{es:"suave/blando",de:"weich",article:"",emoji:"🧸",pron:"[vaɪç]"},
{es:"duro",de:"hart",article:"",emoji:"🪨",pron:"[hart]"},
{es:"dulce",de:"süß",article:"",emoji:"🍬",pron:"[zyːs]"},
{es:"amargo",de:"bitter",article:"",emoji:"😖",pron:"[ˈbɪtɐ]"},
{es:"picante",de:"scharf",article:"",emoji:"🌶️",pron:"[ʃarf]"},
{es:"suave (sabor)",de:"mild",article:"",emoji:"🥗",pron:"[mɪlt]"},
{es:"fresco",de:"frisch",article:"",emoji:"🥬",pron:"[frɪʃ]"},
{es:"sucio",de:"schmutzig",article:"",emoji:"🧹",pron:"[ˈʃmʊtsɪç]"},
{es:"limpio",de:"sauber",article:"",emoji:"✨",pron:"[ˈzaʊbɐ]"},
{es:"estrecho/apretado",de:"eng",article:"",emoji:"📏",pron:"[ɛŋ]"},
{es:"ancho",de:"breit",article:"",emoji:"↔️",pron:"[braɪt]"},
{es:"profundo",de:"tief",article:"",emoji:"⬇️",pron:"[tiːf]"},
{es:"alto (edificio)",de:"hoch",article:"",emoji:"🏢",pron:"[hoːx]"},
{es:"redondo",de:"rund",article:"",emoji:"⭕",pron:"[rʊnt]"},
],
"Comunicación 💬":[
{es:"la opinión",de:"die Meinung",article:"die",emoji:"💭",pron:"[ˈmaɪnʊŋ]"},
{es:"opinar",de:"meinen",article:"",emoji:"🤔",pron:"[ˈmaɪnən]"},
{es:"contar/narrar",de:"erzählen",article:"",emoji:"📖",pron:"[ɛɐ̯ˈtsɛːlən]"},
{es:"mentir",de:"lügen",article:"",emoji:"🤥",pron:"[ˈlyːɡn̩]"},
{es:"prometer",de:"versprechen",article:"",emoji:"🤝",pron:"[fɛɐ̯ˈʃprɛçn̩]"},
{es:"discutir/debatir",de:"diskutieren",article:"",emoji:"🗣️",pron:"[dɪskuˈtiːrən]"},
{es:"comunicar/avisar",de:"mitteilen",article:"",emoji:"📢",pron:"[ˈmɪttaɪlən]"},
{es:"informar",de:"informieren",article:"",emoji:"ℹ️",pron:"[ɪnfɔrˈmiːrən]"},
{es:"notar/darse cuenta",de:"merken",article:"",emoji:"👀",pron:"[ˈmɛrkn̩]"},
{es:"el mensaje",de:"die Nachricht",article:"die",emoji:"💌",pron:"[ˈnaːxrɪçt]"},
{es:"la conversación",de:"das Gespräch",article:"das",emoji:"💬",pron:"[ɡəˈʃprɛːç]"},
{es:"el buzón de voz",de:"die Mailbox",article:"die",emoji:"📨",pron:"[ˈmeɪlbɔks]"},
{es:"la revista",de:"die Zeitschrift",article:"die",emoji:"📰",pron:"[ˈtsaɪtʃrɪft]"},
{es:"la noticia",de:"die Nachricht",article:"die",emoji:"📰",pron:"[ˈnaːxrɪçt]"},
{es:"la página web",de:"die Webseite",article:"die",emoji:"🌐",pron:"[ˈvɛpzaɪtə]"},
],
"Tiempo y frecuencia ⏰":[
{es:"temprano",de:"früh",article:"",emoji:"🌅",pron:"[fryː]"},
{es:"tarde",de:"spät",article:"",emoji:"🌙",pron:"[ʃpɛːt]"},
{es:"finalmente",de:"endlich",article:"",emoji:"🎉",pron:"[ˈɛntlɪç]"},
{es:"al menos",de:"mindestens",article:"",emoji:"📊",pron:"[ˈmɪndəstəns]"},
{es:"casi nunca",de:"selten",article:"",emoji:"🤏",pron:"[ˈzɛltn̩]"},
{es:"normalmente",de:"normalerweise",article:"",emoji:"📅",pron:"[nɔrˈmaːlɐvaɪzə]"},
{es:"de repente",de:"plötzlich",article:"",emoji:"⚡",pron:"[ˈplœtslɪç]"},
{es:"mientras tanto",de:"inzwischen",article:"",emoji:"⏳",pron:"[ɪnˈtsvɪʃn̩]"},
{es:"por primera vez",de:"zum ersten Mal",article:"",emoji:"1️⃣",pron:""},
{es:"la próxima vez",de:"nächstes Mal",article:"",emoji:"➡️",pron:""},
{es:"cada día",de:"täglich",article:"",emoji:"📆",pron:"[ˈtɛːklɪç]"},
{es:"mensual",de:"monatlich",article:"",emoji:"📅",pron:"[ˈmoːnatlɪç]"},
{es:"anterior",de:"vorig",article:"",emoji:"⬅️",pron:"[ˈfoːrɪç]"},
{es:"siguiente",de:"nächst",article:"",emoji:"➡️",pron:"[nɛːçst]"},
],
"Sociedad y vida 🏛️":[
{es:"el vecino",de:"der Nachbar",article:"der",emoji:"🏘️",pron:"[ˈnaxbaːɐ̯]"},
{es:"el adulto",de:"der Erwachsene",article:"der",emoji:"🧑",pron:"[ɛɐ̯ˈvaksənə]"},
{es:"el joven",de:"der Jugendliche",article:"der",emoji:"👦",pron:"[ˈjuːɡn̩tlɪçə]"},
{es:"el extranjero",de:"der Ausländer",article:"der",emoji:"🌍",pron:"[ˈaʊslɛndɐ]"},
{es:"la asociación/club",de:"der Verein",article:"der",emoji:"🤝",pron:"[fɛɐ̯ˈaɪn]"},
{es:"la ley",de:"das Gesetz",article:"das",emoji:"⚖️",pron:"[ɡəˈzɛts]"},
{es:"el derecho",de:"das Recht",article:"das",emoji:"⚖️",pron:"[rɛçt]"},
{es:"el servicio",de:"der Service",article:"der",emoji:"🛎️",pron:"[ˈzɛrvɪs]"},
{es:"el medio ambiente",de:"die Umwelt",article:"die",emoji:"🌱",pron:"[ˈʊmvɛlt]"},
{es:"la basura",de:"der Müll",article:"der",emoji:"🗑️",pron:"[mʏl]"},
{es:"separar (basura)",de:"trennen",article:"",emoji:"♻️",pron:"[ˈtrɛnən]"},
{es:"el ruido",de:"der Lärm",article:"der",emoji:"🔊",pron:"[lɛrm]"},
{es:"la cultura",de:"die Kultur",article:"die",emoji:"🎭",pron:"[kʊlˈtuːɐ̯]"},
{es:"la religión",de:"die Religion",article:"die",emoji:"🕊️",pron:"[reliˈɡi̯oːn]"},
],
"Tecnología 💻":[
{es:"la aplicación",de:"die App",article:"die",emoji:"📱",pron:"[ɛp]"},
{es:"el blog",de:"der Blog",article:"der",emoji:"📝",pron:"[blɔɡ]"},
{es:"descargar",de:"herunterladen",article:"",emoji:"⬇️",pron:"[hɛˈrʊntɐlaːdn̩]"},
{es:"en línea",de:"online",article:"",emoji:"🌐",pron:"[ˈɔnlaɪn]"},
{es:"la contraseña",de:"das Passwort",article:"das",emoji:"🔑",pron:"[ˈpasvɔrt]"},
{es:"la red social",de:"das soziale Netzwerk",article:"das",emoji:"📲",pron:""},
{es:"buscar (internet)",de:"googeln",article:"",emoji:"🔍",pron:"[ˈɡuːɡl̩n]"},
{es:"el programa",de:"das Programm",article:"das",emoji:"💻",pron:"[proˈɡram]"},
{es:"guardar",de:"speichern",article:"",emoji:"💾",pron:"[ˈʃpaɪçɐn]"},
{es:"borrar",de:"löschen",article:"",emoji:"🗑️",pron:"[ˈlœʃn̩]"},
{es:"imprimir",de:"drucken",article:"",emoji:"🖨️",pron:"[ˈdrʊkn̩]"},
{es:"el archivo",de:"die Datei",article:"die",emoji:"📁",pron:"[daˈtaɪ]"},
{es:"la batería",de:"der Akku",article:"der",emoji:"🔋",pron:"[ˈaku]"},
{es:"cargar (batería)",de:"aufladen",article:"",emoji:"🔌",pron:"[ˈaʊflaːdn̩]"},
],
"Cocina y recetas 🍳":[
{es:"freír",de:"braten",article:"",emoji:"🍳",pron:"[ˈbraːtn̩]"},
{es:"hornear",de:"backen",article:"",emoji:"🧁",pron:"[ˈbakn̩]"},
{es:"cortar",de:"schneiden",article:"",emoji:"🔪",pron:"[ˈʃnaɪdn̩]"},
{es:"mezclar",de:"mischen",article:"",emoji:"🥣",pron:"[ˈmɪʃn̩]"},
{es:"hervir",de:"kochen",article:"",emoji:"♨️",pron:"[ˈkɔxn̩]"},
{es:"la receta",de:"das Rezept",article:"das",emoji:"📋",pron:"[reˈtsɛpt]"},
{es:"el ingrediente",de:"die Zutat",article:"die",emoji:"🥕",pron:"[ˈtsuːtaːt]"},
{es:"la sartén",de:"die Pfanne",article:"die",emoji:"🍳",pron:"[ˈpfanə]"},
{es:"la olla",de:"der Topf",article:"der",emoji:"🫕",pron:"[tɔpf]"},
{es:"el horno",de:"der Ofen",article:"der",emoji:"🔥",pron:"[ˈoːfn̩]"},
{es:"la especia",de:"das Gewürz",article:"das",emoji:"🧂",pron:"[ɡəˈvʏrts]"},
{es:"el aceite",de:"das Öl",article:"das",emoji:"🫒",pron:"[øːl]"},
{es:"el vinagre",de:"der Essig",article:"der",emoji:"🍶",pron:"[ˈɛsɪç]"},
{es:"la harina",de:"das Mehl",article:"das",emoji:"🌾",pron:"[meːl]"},
{es:"el azúcar",de:"der Zucker",article:"der",emoji:"🍬",pron:"[ˈtsʊkɐ]"},
],
"Relaciones 💕":[
{es:"la amistad",de:"die Freundschaft",article:"die",emoji:"🤝",pron:"[ˈfrɔʏntʃaft]"},
{es:"la relación",de:"die Beziehung",article:"die",emoji:"💕",pron:"[bəˈtsiːʊŋ]"},
{es:"enamorarse",de:"sich verlieben",article:"",emoji:"😍",pron:"[zɪç fɛɐ̯ˈliːbn̩]"},
{es:"separarse",de:"sich trennen",article:"",emoji:"💔",pron:"[zɪç ˈtrɛnən]"},
{es:"casarse",de:"heiraten",article:"",emoji:"💍",pron:"[ˈhaɪraːtn̩]"},
{es:"divorciarse",de:"sich scheiden lassen",article:"",emoji:"📋",pron:""},
{es:"la boda",de:"die Hochzeit",article:"die",emoji:"💒",pron:"[ˈhɔxtsaɪt]"},
{es:"el nacimiento",de:"die Geburt",article:"die",emoji:"👶",pron:"[ɡəˈbuːɐ̯t]"},
{es:"la muerte",de:"der Tod",article:"der",emoji:"🕊️",pron:"[toːt]"},
{es:"confiar",de:"vertrauen",article:"",emoji:"🤝",pron:"[fɛɐ̯ˈtraʊən]"},
{es:"respetar",de:"respektieren",article:"",emoji:"🙏",pron:"[rɛspɛkˈtiːrən]"},
{es:"apoyar",de:"unterstützen",article:"",emoji:"💪",pron:"[ʊntɐˈʃtʏtsn̩]"},
],
"Trabajo ampliado 💼":[
{es:"el currículum",de:"der Lebenslauf",article:"der",emoji:"📄",pron:"[ˈleːbn̩slaʊf]"},
{es:"la entrevista",de:"das Vorstellungsgespräch",article:"das",emoji:"🤝",pron:""},
{es:"las horas extra",de:"die Überstunden",article:"die",emoji:"⏰",pron:"[ˈyːbɐʃtʊndn̩]"},
{es:"el compañero",de:"der Mitarbeiter",article:"der",emoji:"👥",pron:"[ˈmɪtarbaɪtɐ]"},
{es:"la reunión",de:"die Besprechung",article:"die",emoji:"📋",pron:"[bəˈʃprɛçʊŋ]"},
{es:"solicitar",de:"sich bewerben",article:"",emoji:"📝",pron:"[zɪç bəˈvɛrbn̩]"},
{es:"la profesión",de:"der Beruf",article:"der",emoji:"💼",pron:"[bəˈruːf]"},
{es:"el jefe",de:"der Chef",article:"der",emoji:"👔",pron:"[ʃɛf]"},
{es:"independiente",de:"selbstständig",article:"",emoji:"🧑‍💼",pron:"[ˈzɛlpstʃtɛndɪç]"},
{es:"desempleado",de:"arbeitslos",article:"",emoji:"📉",pron:"[ˈarbaɪtsloːs]"},
{es:"el puesto",de:"die Stelle",article:"die",emoji:"📌",pron:"[ˈʃtɛlə]"},
{es:"la experiencia",de:"die Erfahrung",article:"die",emoji:"⭐",pron:"[ɛɐ̯ˈfaːrʊŋ]"},
{es:"el contrato",de:"der Vertrag",article:"der",emoji:"📝",pron:"[fɛɐ̯ˈtraːk]"},
{es:"el sindicato",de:"die Gewerkschaft",article:"die",emoji:"✊",pron:"[ɡəˈvɛrkʃaft]"},
],
"Viajes ampliado ✈️":[
{es:"el alojamiento",de:"die Unterkunft",article:"die",emoji:"🏨",pron:"[ˈʊntɐkʊnft]"},
{es:"el apartamento vacacional",de:"die Ferienwohnung",article:"die",emoji:"🏖️",pron:"[ˈfeːriənvoːnʊŋ]"},
{es:"el camping",de:"der Campingplatz",article:"der",emoji:"⛺",pron:"[ˈkɛmpɪŋplats]"},
{es:"la excursión",de:"der Ausflug",article:"der",emoji:"🥾",pron:"[ˈaʊsfluːk]"},
{es:"el monumento",de:"die Sehenswürdigkeit",article:"die",emoji:"🏛️",pron:""},
{es:"el equipaje",de:"das Gepäck",article:"das",emoji:"🧳",pron:"[ɡəˈpɛk]"},
{es:"la maleta",de:"der Koffer",article:"der",emoji:"🧳",pron:"[ˈkɔfɐ]"},
{es:"hacer la maleta",de:"packen",article:"",emoji:"📦",pron:"[ˈpakn̩]"},
{es:"la recepción",de:"die Rezeption",article:"die",emoji:"🛎️",pron:"[reˈtsɛpʦi̯oːn]"},
{es:"la pensión",de:"die Pension",article:"die",emoji:"🏡",pron:"[pɛnˈzi̯oːn]"},
{es:"la media pensión",de:"die Halbpension",article:"die",emoji:"🍽️",pron:"[ˈhalppenzi̯oːn]"},
{es:"la guía turística",de:"der Reiseführer",article:"der",emoji:"📖",pron:"[ˈraɪzəfyːrɐ]"},
{es:"la agencia de viajes",de:"das Reisebüro",article:"das",emoji:"🏢",pron:"[ˈraɪzəbyːro]"},
{es:"el recuerdo/souvenir",de:"das Souvenir",article:"das",emoji:"🎁",pron:"[zuvəˈniːɐ̯]"},
],
};

const SENTENCES_A2 = [
{de:"Ich habe gestern einen Film gesehen",es:"Ayer vi una película",hint:"Perfekt"},
{de:"Wir sind letztes Jahr nach Italien gefahren",es:"Fuimos a Italia el año pasado",hint:"Perfekt con sein"},
{de:"Er hat den ganzen Tag gearbeitet",es:"Él trabajó todo el día",hint:"Perfekt"},
{de:"Ich würde gern nach Japan reisen",es:"Me gustaría viajar a Japón",hint:"Konjunktiv II"},
{de:"Könnten Sie mir den Weg zeigen",es:"¿Podría indicarme el camino?",hint:"Konjunktiv II formal"},
{de:"Wenn ich Zeit hätte würde ich lesen",es:"Si tuviera tiempo leería",hint:"Konjunktiv II"},
{de:"Ich muss zum Arzt gehen",es:"Tengo que ir al médico",hint:"Modalverben"},
{de:"Man darf hier nicht rauchen",es:"No se puede fumar aquí",hint:"Modalverben"},
{de:"Du solltest mehr Wasser trinken",es:"Deberías beber más agua",hint:"Modalverben"},
{de:"Ich freue mich auf den Urlaub",es:"Me alegro por las vacaciones",hint:"reflexive Verben"},
{de:"Er interessiert sich für Musik",es:"Él se interesa por la música",hint:"reflexive Verben"},
{de:"Wir haben uns gestern getroffen",es:"Nos encontramos ayer",hint:"reflexive Verben"},
{de:"Das Buch das ich lese ist spannend",es:"El libro que leo es emocionante",hint:"Relativsätze"},
{de:"Die Frau die dort steht ist meine Chefin",es:"La mujer que está ahí es mi jefa",hint:"Relativsätze"},
{de:"Ich bin müde weil ich schlecht geschlafen habe",es:"Estoy cansado porque dormí mal",hint:"Nebensätze"},
{de:"Er sagt dass er morgen kommt",es:"Él dice que viene mañana",hint:"dass-Satz"},
{de:"Obwohl es regnet gehen wir spazieren",es:"Aunque llueve vamos a pasear",hint:"Nebensätze"},
{de:"Ich habe Kopfschmerzen seit heute Morgen",es:"Tengo dolor de cabeza desde esta mañana",hint:"Gesundheit"},
{de:"Der Arzt hat mir Tabletten verschrieben",es:"El médico me recetó pastillas",hint:"Gesundheit"},
{de:"Können wir einen Termin vereinbaren",es:"¿Podemos acordar una cita?",hint:"Arbeit"},
{de:"Ich habe mich für die Stelle beworben",es:"Me postulé para el puesto",hint:"Arbeit"},
{de:"Die Wohnung hat drei Zimmer und einen Balkon",es:"El piso tiene tres habitaciones y un balcón",hint:"Wohnung"},
{de:"Wir müssen den Mietvertrag unterschreiben",es:"Tenemos que firmar el contrato de alquiler",hint:"Wohnung"},
{de:"Ich bin seit fünf Jahren in Deutschland",es:"Estoy en Alemania desde hace cinco años",hint:"seit + Dativ"},
{de:"Nachdem ich gegessen hatte ging ich schlafen",es:"Después de comer me fui a dormir",hint:"Plusquamperfekt"},
];

const VERBS_A2 = [
{inf:"sich freuen",es:"alegrarse",type:"reflexive",conj:{ich:"freue mich",du:"freust dich","er/sie/es":"freut sich",wir:"freuen uns",ihr:"freut euch","sie/Sie":"freuen sich"}},
{inf:"sich interessieren",es:"interesarse",type:"reflexive",conj:{ich:"interessiere mich",du:"interessierst dich","er/sie/es":"interessiert sich",wir:"interessieren uns",ihr:"interessiert euch","sie/Sie":"interessieren sich"}},
{inf:"sich fühlen",es:"sentirse",type:"reflexive",conj:{ich:"fühle mich",du:"fühlst dich","er/sie/es":"fühlt sich",wir:"fühlen uns",ihr:"fühlt euch","sie/Sie":"fühlen sich"}},
{inf:"sich treffen",es:"encontrarse/quedar",type:"reflexive",conj:{ich:"treffe mich",du:"triffst dich","er/sie/es":"trifft sich",wir:"treffen uns",ihr:"trefft euch","sie/Sie":"treffen sich"}},
{inf:"sich bewerben",es:"postularse",type:"reflexive",conj:{ich:"bewerbe mich",du:"bewirbst dich","er/sie/es":"bewirbt sich",wir:"bewerben uns",ihr:"bewerbt euch","sie/Sie":"bewerben sich"}},
{inf:"anrufen",es:"llamar por teléfono",type:"separable",conj:{ich:"rufe an",du:"rufst an","er/sie/es":"ruft an",wir:"rufen an",ihr:"ruft an","sie/Sie":"rufen an"}},
{inf:"aufstehen",es:"levantarse",type:"separable",conj:{ich:"stehe auf",du:"stehst auf","er/sie/es":"steht auf",wir:"stehen auf",ihr:"steht auf","sie/Sie":"stehen auf"}},
{inf:"einkaufen",es:"hacer compras",type:"separable",conj:{ich:"kaufe ein",du:"kaufst ein","er/sie/es":"kauft ein",wir:"kaufen ein",ihr:"kauft ein","sie/Sie":"kaufen ein"}},
{inf:"anfangen",es:"empezar",type:"separable",conj:{ich:"fange an",du:"fängst an","er/sie/es":"fängt an",wir:"fangen an",ihr:"fangt an","sie/Sie":"fangen an"}},
{inf:"einladen",es:"invitar",type:"separable",conj:{ich:"lade ein",du:"lädst ein","er/sie/es":"lädt ein",wir:"laden ein",ihr:"ladet ein","sie/Sie":"laden ein"}},
{inf:"fernsehen",es:"ver televisión",type:"separable",conj:{ich:"sehe fern",du:"siehst fern","er/sie/es":"sieht fern",wir:"sehen fern",ihr:"seht fern","sie/Sie":"sehen fern"}},
{inf:"umziehen",es:"mudarse",type:"separable",conj:{ich:"ziehe um",du:"ziehst um","er/sie/es":"zieht um",wir:"ziehen um",ihr:"zieht um","sie/Sie":"ziehen um"}},
{inf:"mitnehmen",es:"llevar consigo",type:"separable",conj:{ich:"nehme mit",du:"nimmst mit","er/sie/es":"nimmt mit",wir:"nehmen mit",ihr:"nehmt mit","sie/Sie":"nehmen mit"}},
{inf:"verstehen",es:"entender",type:"inseparable",conj:{ich:"verstehe",du:"verstehst","er/sie/es":"versteht",wir:"verstehen",ihr:"versteht","sie/Sie":"verstehen"}},
{inf:"empfehlen",es:"recomendar",type:"inseparable",conj:{ich:"empfehle",du:"empfiehlst","er/sie/es":"empfiehlt",wir:"empfehlen",ihr:"empfehlt","sie/Sie":"empfehlen"}},
{inf:"beschreiben",es:"describir",type:"inseparable",conj:{ich:"beschreibe",du:"beschreibst","er/sie/es":"beschreibt",wir:"beschreiben",ihr:"beschreibt","sie/Sie":"beschreiben"}},
{inf:"erklären",es:"explicar",type:"inseparable",conj:{ich:"erkläre",du:"erklärst","er/sie/es":"erklärt",wir:"erklären",ihr:"erklärt","sie/Sie":"erklären"}},
{inf:"vergleichen",es:"comparar",type:"inseparable",conj:{ich:"vergleiche",du:"vergleichst","er/sie/es":"vergleicht",wir:"vergleichen",ihr:"vergleicht","sie/Sie":"vergleichen"}},
{inf:"denken",es:"pensar",type:"irregular",conj:{ich:"denke",du:"denkst","er/sie/es":"denkt",wir:"denken",ihr:"denkt","sie/Sie":"denken"}},
{inf:"bringen",es:"traer",type:"irregular",conj:{ich:"bringe",du:"bringst","er/sie/es":"bringt",wir:"bringen",ihr:"bringt","sie/Sie":"bringen"}},
{inf:"kennen",es:"conocer",type:"irregular",conj:{ich:"kenne",du:"kennst","er/sie/es":"kennt",wir:"kennen",ihr:"kennt","sie/Sie":"kennen"}},
{inf:"vergessen",es:"olvidar",type:"stem-change",conj:{ich:"vergesse",du:"vergisst","er/sie/es":"vergisst",wir:"vergessen",ihr:"vergesst","sie/Sie":"vergessen"}},
{inf:"vorschlagen",es:"proponer",type:"separable",conj:{ich:"schlage vor",du:"schlägst vor","er/sie/es":"schlägt vor",wir:"schlagen vor",ihr:"schlagt vor","sie/Sie":"schlagen vor"}},
];

const PLURALS_A2 = [
{singular:"die Wohnung",plural:"die Wohnungen",es:"piso(s)",rule:"-en",emoji:"🏢"},
{singular:"der Vertrag",plural:"die Verträge",es:"contrato(s)",rule:"-̈e",emoji:"📄"},
{singular:"die Bewerbung",plural:"die Bewerbungen",es:"solicitud(es)",rule:"-en",emoji:"📋"},
{singular:"der Termin",plural:"die Termine",es:"cita(s)",rule:"-e",emoji:"📅"},
{singular:"das Gespräch",plural:"die Gespräche",es:"conversación(es)",rule:"-e",emoji:"💬"},
{singular:"die Erfahrung",plural:"die Erfahrungen",es:"experiencia(s)",rule:"-en",emoji:"🎓"},
{singular:"der Vorschlag",plural:"die Vorschläge",es:"propuesta(s)",rule:"-̈e",emoji:"💡"},
{singular:"das Ergebnis",plural:"die Ergebnisse",es:"resultado(s)",rule:"-se",emoji:"📊"},
{singular:"die Möglichkeit",plural:"die Möglichkeiten",es:"posibilidad(es)",rule:"-en",emoji:"🔓"},
{singular:"der Unterschied",plural:"die Unterschiede",es:"diferencia(s)",rule:"-e",emoji:"↔️"},
{singular:"das Dokument",plural:"die Dokumente",es:"documento(s)",rule:"-e",emoji:"📑"},
{singular:"die Veranstaltung",plural:"die Veranstaltungen",es:"evento(s)",rule:"-en",emoji:"🎪"},
{singular:"der Kollege",plural:"die Kollegen",es:"colega(s)",rule:"-n",emoji:"👔"},
{singular:"das Angebot",plural:"die Angebote",es:"oferta(s)",rule:"-e",emoji:"🏷️"},
{singular:"die Übung",plural:"die Übungen",es:"ejercicio(s)",rule:"-en",emoji:"📝"},
{singular:"der Ausflug",plural:"die Ausflüge",es:"excursión(es)",rule:"-̈e",emoji:"🚌"},
{singular:"das Museum",plural:"die Museen",es:"museo(s)",rule:"-en",emoji:"🏛️"},
{singular:"die Sehenswürdigkeit",plural:"die Sehenswürdigkeiten",es:"atracción(es)",rule:"-en",emoji:"🗽"},
{singular:"der Ratschlag",plural:"die Ratschläge",es:"consejo(s)",rule:"-̈e",emoji:"🗣️"},
{singular:"das Rezept",plural:"die Rezepte",es:"receta(s)",rule:"-e",emoji:"🧾"},
];

const CASES_A2 = [
{sentence:"Ich erinnere mich an ___ Tag.",opts:["den","dem","der","das"],correct:0,case:"Akkusativ",es:"Recuerdo ese día.",tip:"sich erinnern an + Akkusativ. Masculino: der → <b>den</b>"},
{sentence:"Er wartet auf ___ Bus.",opts:["den","dem","der","das"],correct:0,case:"Akkusativ",es:"Él espera el autobús.",tip:"warten auf + Akkusativ. Masculino: der → <b>den</b>"},
{sentence:"Sie interessiert sich für ___ Stelle.",opts:["die","der","dem","den"],correct:0,case:"Akkusativ",es:"Ella se interesa por el puesto.",tip:"sich interessieren für + Akkusativ. Femenino: die → <b>die</b>"},
{sentence:"Ich freue mich auf ___ Urlaub.",opts:["den","dem","der","das"],correct:0,case:"Akkusativ",es:"Me alegro por las vacaciones.",tip:"sich freuen auf + Akkusativ (futuro). Masculino: der → <b>den</b>"},
{sentence:"Er hat Angst vor ___ Prüfung.",opts:["der","die","dem","den"],correct:0,case:"Dativ",es:"Tiene miedo del examen.",tip:"Angst vor + Dativ. Femenino: die → <b>der</b>"},
{sentence:"Wir sprechen über ___ Problem.",opts:["das","dem","den","der"],correct:0,case:"Akkusativ",es:"Hablamos sobre el problema.",tip:"sprechen über + Akkusativ. Neutro: das → <b>das</b>"},
{sentence:"Das Bild hängt an ___ Wand.",opts:["der","die","dem","den"],correct:0,case:"Dativ",es:"El cuadro cuelga en la pared.",tip:"an + Dativ (ubicación/wo?). Femenino: die → <b>der</b>"},
{sentence:"Er hängt das Bild an ___ Wand.",opts:["die","der","dem","den"],correct:0,case:"Akkusativ",es:"Él cuelga el cuadro en la pared.",tip:"an + Akkusativ (dirección/wohin?). Femenino: die → <b>die</b>"},
{sentence:"Die Katze liegt unter ___ Tisch.",opts:["dem","den","der","das"],correct:0,case:"Dativ",es:"El gato está bajo la mesa.",tip:"unter + Dativ (ubicación/wo?). Masculino: der → <b>dem</b>"},
{sentence:"Er legt das Buch auf ___ Tisch.",opts:["den","dem","der","das"],correct:0,case:"Akkusativ",es:"Él pone el libro sobre la mesa.",tip:"auf + Akkusativ (dirección/wohin?). Masculino: der → <b>den</b>"},
{sentence:"Das Buch liegt auf ___ Tisch.",opts:["dem","den","der","das"],correct:0,case:"Dativ",es:"El libro está sobre la mesa.",tip:"auf + Dativ (ubicación/wo?). Masculino: der → <b>dem</b>"},
{sentence:"Trotz ___ Regens gehen wir spazieren.",opts:["des","dem","den","der"],correct:0,case:"Genitiv",es:"A pesar de la lluvia paseamos.",tip:"trotz + Genitiv. Masculino/Neutro: der/das → <b>des</b> (+s al sustantivo)"},
{sentence:"Während ___ Unterrichts darf man nicht essen.",opts:["des","dem","den","der"],correct:0,case:"Genitiv",es:"Durante la clase no se puede comer.",tip:"während + Genitiv. Masculino: der → <b>des</b> (+s al sustantivo)"},
{sentence:"Wegen ___ Krankheit bleibt er zu Hause.",opts:["der","die","dem","den"],correct:0,case:"Genitiv",es:"Por la enfermedad se queda en casa.",tip:"wegen + Genitiv. Femenino: die → <b>der</b>"},
{sentence:"Er träumt von ___ Reise.",opts:["der","die","dem","den"],correct:0,case:"Dativ",es:"Él sueña con el viaje.",tip:"träumen von + Dativ. Femenino: die → <b>der</b>"},
{sentence:"Ich gratuliere ___ Freundin zum Geburtstag.",opts:["der","die","dem","den"],correct:0,case:"Dativ",es:"Felicito a la amiga por su cumpleaños.",tip:"gratulieren + Dativ. Femenino: die → <b>der</b>"},
{sentence:"Er stellt die Blumen neben ___ Fenster.",opts:["das","dem","den","der"],correct:0,case:"Akkusativ",es:"Pone las flores al lado de la ventana.",tip:"neben + Akkusativ (dirección/wohin?). Neutro: das → <b>das</b>"},
{sentence:"Die Blumen stehen neben ___ Fenster.",opts:["dem","das","den","der"],correct:0,case:"Dativ",es:"Las flores están al lado de la ventana.",tip:"neben + Dativ (ubicación/wo?). Neutro: das → <b>dem</b>"},
{sentence:"Sie kümmert sich um ___ Kinder.",opts:["die","den","dem","der"],correct:0,case:"Akkusativ",es:"Ella se ocupa de los niños.",tip:"sich kümmern um + Akkusativ. Plural: <b>die</b>"},
{sentence:"Ich bin stolz auf ___ Ergebnis.",opts:["das","dem","den","der"],correct:0,case:"Akkusativ",es:"Estoy orgulloso del resultado.",tip:"stolz auf + Akkusativ. Neutro: das → <b>das</b>"},
];

const LISTENING_A2 = [
{id:"listen_wohnung",title:"Wohnungsbesichtigung",desc:"Visitando un apartamento",
dialogue:[
{speaker:"A",de:"Guten Tag, ich habe wegen der Wohnung angerufen."},
{speaker:"B",de:"Ja, kommen Sie herein. Die Wohnung hat drei Zimmer, eine Küche und ein Bad."},
{speaker:"A",de:"Wie hoch ist die Miete?"},
{speaker:"B",de:"Siebenhundertfünfzig Euro warm, inklusive Nebenkosten."},
{speaker:"A",de:"Ab wann ist die Wohnung frei?"},
{speaker:"B",de:"Ab dem ersten August."},
{speaker:"A",de:"Gibt es einen Balkon?"},
{speaker:"B",de:"Ja, der Balkon ist im Wohnzimmer. Er geht nach Süden, deshalb ist die Wohnung sehr hell."},
{speaker:"A",de:"Das gefällt mir. Kann ich den Mietvertrag nächste Woche unterschreiben?"},
{speaker:"B",de:"Natürlich, rufen Sie mich einfach an."},
],quiz:[
{q:"¿Cuántos Zimmer hat die Wohnung?",opts:["Zwei","Drei","Vier","Fünf"],correct:1},
{q:"¿Cuánto cuesta die Miete?",opts:["650 €","700 €","750 €","800 €"],correct:2},
{q:"¿Ab wann ist die Wohnung frei?",opts:["Ab Juli","Ab August","Ab September","Sofort"],correct:1},
{q:"¿Por qué ist die Wohnung hell?",opts:["Große Fenster","Balkon nach Süden","Weiße Wände","Viele Lampen"],correct:1},
]},
{id:"listen_bewerbung",title:"Vorstellungsgespräch",desc:"Entrevista de trabajo",
dialogue:[
{speaker:"A",de:"Guten Tag, Frau Schmidt. Erzählen Sie mir bitte etwas über Ihre Berufserfahrung."},
{speaker:"B",de:"Ich habe fünf Jahre als Verkäuferin gearbeitet."},
{speaker:"A",de:"Warum möchten Sie die Stelle wechseln?"},
{speaker:"B",de:"Weil ich mich beruflich weiterentwickeln möchte. Ich interessiere mich sehr für Marketing."},
{speaker:"A",de:"Können Sie auch am Wochenende arbeiten?"},
{speaker:"B",de:"Ja, samstags kann ich arbeiten, aber sonntags leider nicht."},
{speaker:"A",de:"Wann könnten Sie anfangen?"},
{speaker:"B",de:"Ich könnte ab dem fünfzehnten März anfangen."},
],quiz:[
{q:"¿Cuántos Jahre Berufserfahrung hat Frau Schmidt?",opts:["Drei","Vier","Fünf","Sechs"],correct:2},
{q:"¿Por qué möchte sie die Stelle wechseln?",opts:["Mehr Geld","Weiterentwicklung","Näher wohnen","Weniger arbeiten"],correct:1},
{q:"¿Kann sie am Sonntag arbeiten?",opts:["Ja","Nein","Manchmal","Nur vormittags"],correct:1},
{q:"¿Wann könnte sie anfangen?",opts:["Sofort","Ab 1. März","Ab 15. März","Ab April"],correct:2},
]},
{id:"listen_reisebuero",title:"Im Reisebüro",desc:"En la agencia de viajes",
dialogue:[
{speaker:"A",de:"Guten Tag, ich möchte einen Urlaub buchen."},
{speaker:"B",de:"Gern! Wohin möchten Sie denn reisen?"},
{speaker:"A",de:"Nach Spanien, am liebsten ans Meer."},
{speaker:"B",de:"Wann möchten Sie fahren?"},
{speaker:"A",de:"Im Juli, für zwei Wochen."},
{speaker:"B",de:"Ich habe ein gutes Angebot: eine Woche Mallorca, Flug und Hotel, für achthundertfünfzig Euro pro Person."},
{speaker:"A",de:"Das klingt gut. Ist Frühstück inklusive?"},
{speaker:"B",de:"Ja, Halbpension: Frühstück und Abendessen."},
{speaker:"A",de:"Perfekt, ich nehme es für zwei Personen."},
],quiz:[
{q:"¿Wohin möchte der Kunde reisen?",opts:["Italien","Frankreich","Spanien","Griechenland"],correct:2},
{q:"¿Wann möchte er fahren?",opts:["Im Juni","Im Juli","Im August","Im September"],correct:1},
{q:"¿Wie viel kostet das Angebot pro Person?",opts:["750 €","800 €","850 €","900 €"],correct:2},
{q:"¿Was ist inklusive?",opts:["Nur Frühstück","Vollpension","Halbpension","Nichts"],correct:2},
]},
{id:"listen_radiosendung",title:"Radiosendung",desc:"Anuncio de radio sobre un evento",
dialogue:[
{speaker:"📻",de:"Liebe Hörerinnen und Hörer, am nächsten Samstag findet das große Stadtfest in der Innenstadt statt. Von zehn bis zweiundzwanzig Uhr gibt es Live-Musik, Essen aus aller Welt und ein Programm für Kinder. Der Eintritt ist frei! Bei Regen findet das Fest in der Stadthalle statt. Mehr Informationen auf unserer Webseite."},
],quiz:[
{q:"¿Wann findet das Stadtfest statt?",opts:["Am Freitag","Am Samstag","Am Sonntag","Am Montag"],correct:1},
{q:"¿Wie lange dauert es?",opts:["10-18 Uhr","10-20 Uhr","10-22 Uhr","12-22 Uhr"],correct:2},
{q:"¿Wie viel kostet der Eintritt?",opts:["5 €","10 €","Frei","20 €"],correct:2},
{q:"¿Was passiert bei Regen?",opts:["Es fällt aus","Es ist in der Stadthalle","Es ist am Sonntag","Nichts ändert sich"],correct:1},
]},
];

const WRITING_A2 = [
{id:"write_beschwerde",title:"Beschwerdebrief",desc:"Escribe una queja formal al casero",
scenario:"Tu calefacción no funciona desde hace una semana. Escribe un email formal a tu casero Herr Weber (~50 palabras):",
hints:["Describe el problema","Di desde cuándo ocurre","Pide que lo arreglen pronto"],
keywords:["heizung","funktioniert","nicht","seit","woche","reparieren","bitte","kalt","wohnung","problem"],
example:"Sehr geehrter Herr Weber, ich schreibe Ihnen, weil die Heizung in meiner Wohnung seit einer Woche nicht funktioniert. Es ist sehr kalt und ich bitte Sie, das Problem so schnell wie möglich zu reparieren. Mit freundlichen Grüßen, [Name]"},
{id:"write_bewerbung",title:"Bewerbungsmail",desc:"Escribe un email postulándote a un trabajo",
scenario:"Has visto una oferta de trabajo como Verkäufer/in. Escribe un email corto (~50 palabras):",
hints:["Menciona la oferta que viste","Di tu experiencia","Di cuándo puedes empezar"],
keywords:["stelle","anzeige","erfahrung","jahre","gearbeitet","anfangen","bewerbung","interessiere","verkäufer"],
example:"Sehr geehrte Damen und Herren, ich habe Ihre Anzeige für die Stelle als Verkäuferin gelesen und möchte mich bewerben. Ich habe drei Jahre Erfahrung im Verkauf. Ich könnte ab sofort anfangen. Mit freundlichen Grüßen, [Name]"},
];