// A1 VOCABULARY
const VOCAB_A1 = {
"Familia 👨‍👩‍👧":[
{es:"la madre",de:"die Mutter",article:"die",emoji:"👩",pron:"[mʊtɐ]"},
{es:"el padre",de:"der Vater",article:"der",emoji:"👨",pron:"[faːtɐ]"},
{es:"la hermana",de:"die Schwester",article:"die",emoji:"👧",pron:"[ʃvɛstɐ]"},
{es:"el hermano",de:"der Bruder",article:"der",emoji:"👦",pron:"[bruːdɐ]"},
{es:"la abuela",de:"die Großmutter",article:"die",emoji:"👵",pron:"[groːsmʊtɐ]"},
{es:"el abuelo",de:"der Großvater",article:"der",emoji:"👴",pron:"[groːsfaːtɐ]"},
{es:"el hijo",de:"der Sohn",article:"der",emoji:"👦",pron:"[zoːn]"},
{es:"la hija",de:"die Tochter",article:"die",emoji:"👧",pron:"[tɔxtɐ]"},
{es:"el bebé",de:"das Baby",article:"das",emoji:"👶",pron:"[beːbi]"},
{es:"el esposo",de:"der Ehemann",article:"der",emoji:"🤵",pron:"[eːəman]"},
{es:"la esposa",de:"die Ehefrau",article:"die",emoji:"👰",pron:"[eːəfraʊ]"},
{es:"la tía",de:"die Tante",article:"die",emoji:"👩",pron:"[tantə]"},
{es:"el tío",de:"der Onkel",article:"der",emoji:"👨",pron:"[ɔŋkl̩]"},
{es:"la prima",de:"die Cousine",article:"die",emoji:"👧",pron:"[kuziːnə]"},
{es:"el nieto",de:"der Enkel",article:"der",emoji:"👦",pron:"[ɛŋkl̩]"},
{es:"la abuelita",de:"die Oma",article:"die",emoji:"👵",pron:"[ˈoːma]"},
{es:"el abuelito",de:"der Opa",article:"der",emoji:"👴",pron:"[ˈoːpa]"},
{es:"los hermanos",de:"die Geschwister",article:"die",emoji:"👫",pron:"[ɡəˈʃvɪstɐ]"},
{es:"el hombre",de:"der Mann",article:"der",emoji:"👨",pron:"[man]"},
{es:"la mujer",de:"die Frau",article:"die",emoji:"👩",pron:"[fraʊ]"},
{es:"el niño/a",de:"das Kind",article:"das",emoji:"🧒",pron:"[kɪnt]"},
{es:"los padres",de:"die Eltern",article:"die",emoji:"👨‍👩‍👧",pron:"[ˈɛltɐn]"},
],
"Comida 🍎":[
{es:"la manzana",de:"der Apfel",article:"der",emoji:"🍎",pron:"[apfl̩]"},
{es:"el pan",de:"das Brot",article:"das",emoji:"🍞",pron:"[broːt]"},
{es:"el queso",de:"der Käse",article:"der",emoji:"🧀",pron:"[kɛːzə]"},
{es:"la leche",de:"die Milch",article:"die",emoji:"🥛",pron:"[mɪlç]"},
{es:"el huevo",de:"das Ei",article:"das",emoji:"🥚",pron:"[aɪ]"},
{es:"la mantequilla",de:"die Butter",article:"die",emoji:"🧈",pron:"[bʊtɐ]"},
{es:"el pollo",de:"das Hähnchen",article:"das",emoji:"🍗",pron:"[hɛːnçən]"},
{es:"el pescado",de:"der Fisch",article:"der",emoji:"🐟",pron:"[fɪʃ]"},
{es:"el arroz",de:"der Reis",article:"der",emoji:"🍚",pron:"[raɪs]"},
{es:"la patata",de:"die Kartoffel",article:"die",emoji:"🥔",pron:"[kartɔfl̩]"},
{es:"el tomate",de:"die Tomate",article:"die",emoji:"🍅",pron:"[tomaːtə]"},
{es:"la zanahoria",de:"die Karotte",article:"die",emoji:"🥕",pron:"[kaˈrɔtə]"},
{es:"la fresa",de:"die Erdbeere",article:"die",emoji:"🍓",pron:"[eːɐ̯tbeːrə]"},
{es:"el plátano",de:"die Banane",article:"die",emoji:"🍌",pron:"[baˈnaːnə]"},
{es:"la naranja",de:"die Orange",article:"die",emoji:"🍊",pron:"[oˈrãːʒə]"},
],
"Casa 🏠":[
{es:"la cocina",de:"die Küche",article:"die",emoji:"🍳",pron:"[kʏçə]"},
{es:"el dormitorio",de:"das Schlafzimmer",article:"das",emoji:"🛏️",pron:"[ʃlaːftsɪmɐ]"},
{es:"el baño",de:"das Badezimmer",article:"das",emoji:"🛁",pron:"[baːdətsɪmɐ]"},
{es:"la sala de estar",de:"das Wohnzimmer",article:"das",emoji:"🛋️",pron:"[voːntsɪmɐ]"},
{es:"la mesa",de:"der Tisch",article:"der",emoji:"🪑",pron:"[tɪʃ]"},
{es:"la silla",de:"der Stuhl",article:"der",emoji:"💺",pron:"[ʃtuːl]"},
{es:"la cama",de:"das Bett",article:"das",emoji:"🛏️",pron:"[bɛt]"},
{es:"la ventana",de:"das Fenster",article:"das",emoji:"🪟",pron:"[fɛnstɐ]"},
{es:"la puerta",de:"die Tür",article:"die",emoji:"🚪",pron:"[tyːɐ̯]"},
{es:"la lámpara",de:"die Lampe",article:"die",emoji:"💡",pron:"[lampə]"},
{es:"el espejo",de:"der Spiegel",article:"der",emoji:"🪞",pron:"[ʃpiːɡl̩]"},
{es:"la escalera",de:"die Treppe",article:"die",emoji:"🪜",pron:"[trɛpə]"},
{es:"el sofá",de:"das Sofa",article:"das",emoji:"🛋️",pron:"[zoːfa]"},
{es:"la nevera",de:"der Kühlschrank",article:"der",emoji:"🧊",pron:"[kyːlʃraŋk]"},
{es:"el jardín",de:"der Garten",article:"der",emoji:"🌿",pron:"[ɡartn̩]"},
],
"Ropa 👕":[
{es:"la camisa",de:"das Hemd",article:"das",emoji:"👔",pron:"[hɛmt]"},
{es:"el pantalón",de:"die Hose",article:"die",emoji:"👖",pron:"[hoːzə]"},
{es:"el vestido",de:"das Kleid",article:"das",emoji:"👗",pron:"[klaɪt]"},
{es:"el zapato",de:"der Schuh",article:"der",emoji:"👞",pron:"[ʃuː]"},
{es:"el sombrero",de:"der Hut",article:"der",emoji:"🎩",pron:"[huːt]"},
{es:"el abrigo",de:"der Mantel",article:"der",emoji:"🧥",pron:"[mantl̩]"},
{es:"la falda",de:"der Rock",article:"der",emoji:"👗",pron:"[rɔk]"},
{es:"la corbata",de:"die Krawatte",article:"die",emoji:"👔",pron:"[kraˈvatə]"},
{es:"el guante",de:"der Handschuh",article:"der",emoji:"🧤",pron:"[hantʃuː]"},
{es:"la bufanda",de:"der Schal",article:"der",emoji:"🧣",pron:"[ʃaːl]"},
{es:"el calcetín",de:"die Socke",article:"die",emoji:"🧦",pron:"[zɔkə]"},
{es:"la gorra",de:"die Mütze",article:"die",emoji:"🧢",pron:"[mʏtsə]"},
{es:"las gafas",de:"die Brille",article:"die",emoji:"👓",pron:"[brɪlə]"},
{es:"el reloj",de:"die Uhr",article:"die",emoji:"⌚",pron:"[uːɐ̯]"},
{es:"la mochila",de:"der Rucksack",article:"der",emoji:"🎒",pron:"[rʊkzak]"},
],
"Animales 🐾":[
{es:"el perro",de:"der Hund",article:"der",emoji:"🐕",pron:"[hʊnt]"},
{es:"el gato",de:"die Katze",article:"die",emoji:"🐈",pron:"[katsə]"},
{es:"el pájaro",de:"der Vogel",article:"der",emoji:"🐦",pron:"[foːɡl̩]"},
{es:"el caballo",de:"das Pferd",article:"das",emoji:"🐴",pron:"[pfeːɐ̯t]"},
{es:"la vaca",de:"die Kuh",article:"die",emoji:"🐄",pron:"[kuː]"},
{es:"el cerdo",de:"das Schwein",article:"das",emoji:"🐷",pron:"[ʃvaɪn]"},
{es:"el ratón",de:"die Maus",article:"die",emoji:"🐭",pron:"[maʊs]"},
{es:"el pez",de:"der Fisch",article:"der",emoji:"🐠",pron:"[fɪʃ]"},
{es:"la oveja",de:"das Schaf",article:"das",emoji:"🐑",pron:"[ʃaːf]"},
{es:"la gallina",de:"das Huhn",article:"das",emoji:"🐔",pron:"[huːn]"},
{es:"el conejo",de:"das Kaninchen",article:"das",emoji:"🐰",pron:"[kaˈniːnçən]"},
{es:"el oso",de:"der Bär",article:"der",emoji:"🐻",pron:"[bɛːɐ̯]"},
{es:"la mariposa",de:"der Schmetterling",article:"der",emoji:"🦋",pron:"[ʃmɛtɐlɪŋ]"},
{es:"el pato",de:"die Ente",article:"die",emoji:"🦆",pron:"[ɛntə]"},
{es:"la abeja",de:"die Biene",article:"die",emoji:"🐝",pron:"[biːnə]"},
],
"Cuerpo 🧍":[
{es:"la cabeza",de:"der Kopf",article:"der",emoji:"🗣️",pron:"[kɔpf]"},
{es:"el ojo",de:"das Auge",article:"das",emoji:"👁️",pron:"[aʊɡə]"},
{es:"la nariz",de:"die Nase",article:"die",emoji:"👃",pron:"[naːzə]"},
{es:"la boca",de:"der Mund",article:"der",emoji:"👄",pron:"[mʊnt]"},
{es:"la oreja",de:"das Ohr",article:"das",emoji:"👂",pron:"[oːɐ̯]"},
{es:"la mano",de:"die Hand",article:"die",emoji:"✋",pron:"[hant]"},
{es:"el pie",de:"der Fuß",article:"der",emoji:"🦶",pron:"[fuːs]"},
{es:"el diente",de:"der Zahn",article:"der",emoji:"🦷",pron:"[tsaːn]"},
{es:"el pelo",de:"das Haar",article:"das",emoji:"💇",pron:"[haːɐ̯]"},
{es:"el corazón",de:"das Herz",article:"das",emoji:"❤️",pron:"[hɛrts]"},
{es:"el dedo",de:"der Finger",article:"der",emoji:"👆",pron:"[fɪŋɐ]"},
{es:"la rodilla",de:"das Knie",article:"das",emoji:"🦵",pron:"[kniː]"},
{es:"el brazo",de:"der Arm",article:"der",emoji:"💪",pron:"[arm]"},
{es:"la espalda",de:"der Rücken",article:"der",emoji:"🧍",pron:"[rʏkn̩]"},
{es:"el hombro",de:"die Schulter",article:"die",emoji:"🤷",pron:"[ʃʊltɐ]"},
],
"Bebidas ☕":[
{es:"el agua",de:"das Wasser",article:"das",emoji:"💧",pron:"[vasɐ]"},
{es:"el café",de:"der Kaffee",article:"der",emoji:"☕",pron:"[kafeː]"},
{es:"el té",de:"der Tee",article:"der",emoji:"🍵",pron:"[teː]"},
{es:"el zumo",de:"der Saft",article:"der",emoji:"🧃",pron:"[zaft]"},
{es:"la cerveza",de:"das Bier",article:"das",emoji:"🍺",pron:"[biːɐ̯]"},
{es:"el vino",de:"der Wein",article:"der",emoji:"🍷",pron:"[vaɪn]"},
{es:"la limonada",de:"die Limonade",article:"die",emoji:"🍋",pron:"[limoˈnaːdə]"},
{es:"el chocolate",de:"die Schokolade",article:"die",emoji:"🍫",pron:"[ʃokoˈlaːdə]"},
],
"Números 🔢":[
{es:"uno",de:"eins",article:"",emoji:"1️⃣",pron:"[aɪns]"},
{es:"dos",de:"zwei",article:"",emoji:"2️⃣",pron:"[tsvaɪ]"},
{es:"tres",de:"drei",article:"",emoji:"3️⃣",pron:"[draɪ]"},
{es:"cuatro",de:"vier",article:"",emoji:"4️⃣",pron:"[fiːɐ̯]"},
{es:"cinco",de:"fünf",article:"",emoji:"5️⃣",pron:"[fʏnf]"},
{es:"seis",de:"sechs",article:"",emoji:"6️⃣",pron:"[zɛks]"},
{es:"siete",de:"sieben",article:"",emoji:"7️⃣",pron:"[ziːbn̩]"},
{es:"ocho",de:"acht",article:"",emoji:"8️⃣",pron:"[axt]"},
{es:"nueve",de:"neun",article:"",emoji:"9️⃣",pron:"[nɔʏn]"},
{es:"diez",de:"zehn",article:"",emoji:"🔟",pron:"[tseːn]"},
],
"Saludos 👋":[
{es:"¡Hola!",de:"Hallo!",article:"",emoji:"👋",pron:"[haloː]"},
{es:"¡Buenos días!",de:"Guten Morgen!",article:"",emoji:"🌅",pron:"[ɡuːtn̩ mɔrɡn̩]"},
{es:"¡Buenas tardes!",de:"Guten Tag!",article:"",emoji:"☀️",pron:"[ɡuːtn̩ taːk]"},
{es:"¡Buenas noches!",de:"Guten Abend!",article:"",emoji:"🌙",pron:"[ɡuːtn̩ aːbn̩t]"},
{es:"¡Adiós!",de:"Tschüss!",article:"",emoji:"👋",pron:"[tʃʏs]"},
{es:"Hasta la vista",de:"Auf Wiedersehen!",article:"",emoji:"🤝",pron:"[aʊf viːdɐzeːən]"},
{es:"Por favor",de:"Bitte",article:"",emoji:"🙏",pron:"[bɪtə]"},
{es:"Gracias",de:"Danke",article:"",emoji:"😊",pron:"[daŋkə]"},
{es:"De nada",de:"Bitte schön",article:"",emoji:"😄",pron:"[bɪtə ʃøːn]"},
{es:"Perdón",de:"Entschuldigung",article:"",emoji:"😅",pron:"[ɛntʃʊldɪɡʊŋ]"},
{es:"Sí",de:"Ja",article:"",emoji:"✅",pron:"[jaː]"},
{es:"No",de:"Nein",article:"",emoji:"❌",pron:"[naɪn]"},
],
"Transporte 🚗":[
{es:"el coche",de:"das Auto",article:"das",emoji:"🚗",pron:"[aʊto]"},
{es:"el autobús",de:"der Bus",article:"der",emoji:"🚌",pron:"[bʊs]"},
{es:"el tren",de:"der Zug",article:"der",emoji:"🚆",pron:"[tsuːk]"},
{es:"la bicicleta",de:"das Fahrrad",article:"das",emoji:"🚲",pron:"[faːɐ̯raːt]"},
{es:"el avión",de:"das Flugzeug",article:"das",emoji:"✈️",pron:"[fluːktsɔʏk]"},
{es:"el barco",de:"das Schiff",article:"das",emoji:"🚢",pron:"[ʃɪf]"},
{es:"la moto",de:"das Motorrad",article:"das",emoji:"🏍️",pron:"[moːtoːraːt]"},
{es:"el taxi",de:"das Taxi",article:"das",emoji:"🚕",pron:"[taksi]"},
{es:"el metro",de:"die U-Bahn",article:"die",emoji:"🚇",pron:"[uːbaːn]"},
{es:"el semáforo",de:"die Ampel",article:"die",emoji:"🚦",pron:"[ampl̩]"},
{es:"el aeropuerto",de:"der Flughafen",article:"der",emoji:"✈️",pron:"[ˈfluːkhaːfn̩]"},
{es:"la estación",de:"der Bahnhof",article:"der",emoji:"🚉",pron:"[ˈbaːnhoːf]"},
{es:"el andén",de:"der Bahnsteig",article:"der",emoji:"🚏",pron:"[ˈbaːnʃtaɪk]"},
{es:"la parada",de:"die Haltestelle",article:"die",emoji:"🚏",pron:"[ˈhaltəʃtɛlə]"},
{es:"el billete",de:"die Fahrkarte",article:"die",emoji:"🎫",pron:"[ˈfaːɐ̯kartə]"},
{es:"subir (al tren)",de:"einsteigen",article:"",emoji:"🚪",pron:"[ˈaɪnʃtaɪɡn̩]"},
{es:"bajar (del tren)",de:"aussteigen",article:"",emoji:"🚪",pron:"[ˈaʊsʃtaɪɡn̩]"},
{es:"hacer trasbordo",de:"umsteigen",article:"",emoji:"🔄",pron:"[ˈʊmʃtaɪɡn̩]"},
{es:"llegar",de:"ankommen",article:"",emoji:"📍",pron:"[ˈankɔmən]"},
{es:"recoger a alguien",de:"abholen",article:"",emoji:"🤝",pron:"[ˈaphoːlən]"},
],
"Supervivencia 🆘":[
{es:"No entiendo",de:"Ich verstehe nicht",article:"",emoji:"😕",pron:"[ɪç fɛɐˈʃteːə nɪçt]"},
{es:"¿Puede repetir?",de:"Können Sie das bitte wiederholen?",article:"",emoji:"🔁",pron:""},
{es:"¿Habla español?",de:"Sprechen Sie Spanisch?",article:"",emoji:"🇪🇸",pron:""},
{es:"Necesito ayuda",de:"Ich brauche Hilfe",article:"",emoji:"🙋",pron:"[ɪç braʊxə hɪlfə]"},
{es:"¿Dónde está...?",de:"Wo ist...?",article:"",emoji:"📍",pron:"[voː ɪst]"},
{es:"¿Cuánto cuesta?",de:"Wie viel kostet das?",article:"",emoji:"💰",pron:"[viː fiːl kɔstət das]"},
{es:"La cuenta, por favor",de:"Die Rechnung, bitte",article:"",emoji:"🧾",pron:""},
{es:"¿Dónde está el baño?",de:"Wo ist die Toilette?",article:"",emoji:"🚻",pron:""},
{es:"Lo siento",de:"Es tut mir leid",article:"",emoji:"😔",pron:"[ɛs tuːt miːɐ̯ laɪt]"},
{es:"Tengo una pregunta",de:"Ich habe eine Frage",article:"",emoji:"❓",pron:""},
{es:"¿Puede hablar más lento?",de:"Können Sie bitte langsamer sprechen?",article:"",emoji:"🐢",pron:""},
{es:"Estoy perdido/a",de:"Ich habe mich verlaufen",article:"",emoji:"🗺️",pron:""},
{es:"Llame a la policía",de:"Rufen Sie die Polizei",article:"",emoji:"🚔",pron:""},
{es:"Necesito un médico",de:"Ich brauche einen Arzt",article:"",emoji:"🏥",pron:""},
{es:"¿Me puede ayudar?",de:"Können Sie mir helfen?",article:"",emoji:"🤝",pron:""},
{es:"No hablo bien alemán",de:"Ich spreche nicht gut Deutsch",article:"",emoji:"🗣️",pron:""},
{es:"Un momento, por favor",de:"Einen Moment, bitte",article:"",emoji:"⏳",pron:""},
{es:"¿Cómo se dice...?",de:"Wie sagt man...?",article:"",emoji:"💬",pron:""},
{es:"Eso es todo",de:"Das ist alles",article:"",emoji:"✅",pron:""},
{es:"Está bien",de:"Das ist in Ordnung",article:"",emoji:"👍",pron:""},
],
"Clima 🌤️":[
{es:"el sol",de:"die Sonne",article:"die",emoji:"☀️",pron:"[zɔnə]"},
{es:"la lluvia",de:"der Regen",article:"der",emoji:"🌧️",pron:"[reːɡn̩]"},
{es:"la nieve",de:"der Schnee",article:"der",emoji:"❄️",pron:"[ʃneː]"},
{es:"el viento",de:"der Wind",article:"der",emoji:"💨",pron:"[vɪnt]"},
{es:"la nube",de:"die Wolke",article:"die",emoji:"☁️",pron:"[vɔlkə]"},
{es:"la tormenta",de:"das Gewitter",article:"das",emoji:"⛈️",pron:"[ɡəvɪtɐ]"},
{es:"la niebla",de:"der Nebel",article:"der",emoji:"🌫️",pron:"[neːbl̩]"},
{es:"caliente",de:"heiß",article:"",emoji:"🥵",pron:"[haɪs]"},
{es:"frío",de:"kalt",article:"",emoji:"🥶",pron:"[kalt]"},
{es:"cálido",de:"warm",article:"",emoji:"😊",pron:"[varm]"},
{es:"llueve",de:"Es regnet",article:"",emoji:"🌧️",pron:"[ɛs reːɡnət]"},
{es:"nieva",de:"Es schneit",article:"",emoji:"🌨️",pron:"[ɛs ʃnaɪt]"},
{es:"hace sol",de:"Die Sonne scheint",article:"",emoji:"☀️",pron:""},
{es:"el grado",de:"der Grad",article:"der",emoji:"🌡️",pron:"[ɡraːt]"},
{es:"el pronóstico",de:"die Wettervorhersage",article:"die",emoji:"📊",pron:""},
],
"Profesiones 💼":[
{es:"el médico",de:"der Arzt",article:"der",emoji:"👨‍⚕️",pron:"[aːɐ̯tst]"},
{es:"la médica",de:"die Ärztin",article:"die",emoji:"👩‍⚕️",pron:"[ɛːɐ̯tstɪn]"},
{es:"el profesor",de:"der Lehrer",article:"der",emoji:"👨‍🏫",pron:"[leːrɐ]"},
{es:"la profesora",de:"die Lehrerin",article:"die",emoji:"👩‍🏫",pron:"[leːrərɪn]"},
{es:"el vendedor",de:"der Verkäufer",article:"der",emoji:"🧑‍💼",pron:"[fɛɐ̯kɔʏfɐ]"},
{es:"el estudiante",de:"der Student",article:"der",emoji:"👨‍🎓",pron:"[ʃtuˈdɛnt]"},
{es:"el ingeniero",de:"der Ingenieur",article:"der",emoji:"👷",pron:"[ɪnʒeˈni̯øːɐ̯]"},
{es:"el policía",de:"der Polizist",article:"der",emoji:"👮",pron:"[poliˈtsɪst]"},
{es:"el cocinero",de:"der Koch",article:"der",emoji:"👨‍🍳",pron:"[kɔx]"},
{es:"el conductor",de:"der Fahrer",article:"der",emoji:"🚗",pron:"[faːrɐ]"},
{es:"el camarero",de:"der Kellner",article:"der",emoji:"🍽️",pron:"[kɛlnɐ]"},
{es:"el peluquero",de:"der Friseur",article:"der",emoji:"💇",pron:"[friˈzøːɐ̯]"},
{es:"la enfermera",de:"die Krankenschwester",article:"die",emoji:"👩‍⚕️",pron:""},
{es:"el panadero",de:"der Bäcker",article:"der",emoji:"🍞",pron:"[bɛkɐ]"},
{es:"ama de casa",de:"die Hausfrau",article:"die",emoji:"🏠",pron:"[haʊsfraʊ]"},
{es:"la arquitecta",de:"die Architektin",article:"die",emoji:"📐",pron:"[arçiˈtɛktɪn]"},
{es:"el actor",de:"der Schauspieler",article:"der",emoji:"🎭",pron:"[ˈʃaʊʃpiːlɐ]"},
{es:"la secretaria",de:"die Sekretärin",article:"die",emoji:"💻",pron:"[zekreˈtɛːrɪn]"},
{es:"el periodista",de:"der Journalist",article:"der",emoji:"📰",pron:"[ʒʊrnaˈlɪst]"},
{es:"el ama de casa (m)",de:"der Hausmann",article:"der",emoji:"🏠",pron:"[ˈhaʊsman]"},
],
"Adjetivos 📏":[
{es:"grande",de:"groß",article:"",emoji:"📐",pron:"[ɡroːs]"},
{es:"pequeño",de:"klein",article:"",emoji:"🤏",pron:"[klaɪn]"},
{es:"nuevo",de:"neu",article:"",emoji:"✨",pron:"[nɔʏ]"},
{es:"viejo",de:"alt",article:"",emoji:"🏚️",pron:"[alt]"},
{es:"caro",de:"teuer",article:"",emoji:"💎",pron:"[tɔʏɐ]"},
{es:"barato",de:"billig",article:"",emoji:"🏷️",pron:"[bɪlɪç]"},
{es:"bonito",de:"schön",article:"",emoji:"😍",pron:"[ʃøːn]"},
{es:"feo",de:"hässlich",article:"",emoji:"😬",pron:"[hɛslɪç]"},
{es:"rápido",de:"schnell",article:"",emoji:"⚡",pron:"[ʃnɛl]"},
{es:"lento",de:"langsam",article:"",emoji:"🐢",pron:"[laŋzaːm]"},
{es:"fácil",de:"einfach",article:"",emoji:"😌",pron:"[aɪnfax]"},
{es:"difícil",de:"schwer",article:"",emoji:"😰",pron:"[ʃveːɐ̯]"},
{es:"bueno",de:"gut",article:"",emoji:"👍",pron:"[ɡuːt]"},
{es:"malo",de:"schlecht",article:"",emoji:"👎",pron:"[ʃlɛçt]"},
{es:"largo",de:"lang",article:"",emoji:"📏",pron:"[laŋ]"},
{es:"corto",de:"kurz",article:"",emoji:"📎",pron:"[kʊrts]"},
{es:"pesado",de:"schwer",article:"",emoji:"🏋️",pron:"[ʃveːɐ̯]"},
{es:"ligero",de:"leicht",article:"",emoji:"🪶",pron:"[laɪçt]"},
{es:"libre/vacío",de:"frei",article:"",emoji:"🆓",pron:"[fraɪ]"},
{es:"ocupado",de:"besetzt",article:"",emoji:"🚫",pron:"[bəˈzɛtst]"},
],
"Verbos ⚡":[
{es:"ir",de:"gehen",article:"",emoji:"🚶",pron:"[ɡeːən]"},
{es:"venir",de:"kommen",article:"",emoji:"🏃",pron:"[kɔmən]"},
{es:"hacer",de:"machen",article:"",emoji:"🔨",pron:"[maxən]"},
{es:"trabajar",de:"arbeiten",article:"",emoji:"💼",pron:"[arbaɪtn̩]"},
{es:"vivir",de:"wohnen",article:"",emoji:"🏠",pron:"[voːnən]"},
{es:"aprender",de:"lernen",article:"",emoji:"📚",pron:"[lɛrnən]"},
{es:"leer",de:"lesen",article:"",emoji:"📖",pron:"[leːzn̩]"},
{es:"escribir",de:"schreiben",article:"",emoji:"✍️",pron:"[ʃraɪbn̩]"},
{es:"hablar",de:"sprechen",article:"",emoji:"🗣️",pron:"[ʃprɛçən]"},
{es:"comprar",de:"kaufen",article:"",emoji:"🛒",pron:"[kaʊfn̩]"},
{es:"buscar",de:"suchen",article:"",emoji:"🔍",pron:"[zuːxən]"},
{es:"encontrar",de:"finden",article:"",emoji:"💡",pron:"[fɪndən]"},
{es:"dormir",de:"schlafen",article:"",emoji:"😴",pron:"[ʃlaːfn̩]"},
{es:"jugar",de:"spielen",article:"",emoji:"🎮",pron:"[ʃpiːlən]"},
{es:"conducir/viajar",de:"fahren",article:"",emoji:"🚗",pron:"[faːrən]"},
{es:"poder",de:"können",article:"",emoji:"💪",pron:"[kœnən]"},
{es:"deber/tener que",de:"müssen",article:"",emoji:"⚠️",pron:"[mʏsən]"},
{es:"querer",de:"wollen",article:"",emoji:"🎯",pron:"[vɔlən]"},
{es:"gustar",de:"mögen",article:"",emoji:"❤️",pron:"[møːɡn̩]"},
{es:"necesitar",de:"brauchen",article:"",emoji:"🙏",pron:"[braʊxən]"},
],
"Preposiciones 📍":[
{es:"en (lugar cerrado)",de:"in",article:"",emoji:"📦",pron:"[ɪn]"},
{es:"sobre/encima",de:"auf",article:"",emoji:"⬆️",pron:"[aʊf]"},
{es:"delante de",de:"vor",article:"",emoji:"➡️",pron:"[foːɐ̯]"},
{es:"detrás de",de:"hinter",article:"",emoji:"⬅️",pron:"[hɪntɐ]"},
{es:"al lado de",de:"neben",article:"",emoji:"↔️",pron:"[neːbn̩]"},
{es:"entre",de:"zwischen",article:"",emoji:"↕️",pron:"[tsvɪʃən]"},
{es:"debajo de",de:"unter",article:"",emoji:"⬇️",pron:"[ʊntɐ]"},
{es:"encima de",de:"über",article:"",emoji:"🔝",pron:"[yːbɐ]"},
{es:"con",de:"mit",article:"",emoji:"🤝",pron:"[mɪt]"},
{es:"sin",de:"ohne",article:"",emoji:"🚫",pron:"[oːnə]"},
{es:"para",de:"für",article:"",emoji:"🎁",pron:"[fyːɐ̯]"},
{es:"de/desde",de:"von",article:"",emoji:"📤",pron:"[fɔn]"},
{es:"a/hacia",de:"nach",article:"",emoji:"➡️",pron:"[naːx]"},
{es:"hasta",de:"bis",article:"",emoji:"🏁",pron:"[bɪs]"},
{es:"a las (hora)",de:"um",article:"",emoji:"🕐",pron:"[ʊm]"},
],
"Países 🌍":[
{es:"Alemania",de:"Deutschland",article:"",emoji:"🇩🇪",pron:"[dɔʏtʃlant]"},
{es:"Austria",de:"Österreich",article:"",emoji:"🇦🇹",pron:"[ˈøːstɐraɪç]"},
{es:"Suiza",de:"die Schweiz",article:"die",emoji:"🇨🇭",pron:"[ʃvaɪts]"},
{es:"Francia",de:"Frankreich",article:"",emoji:"🇫🇷",pron:"[ˈfraŋkraɪç]"},
{es:"España",de:"Spanien",article:"",emoji:"🇪🇸",pron:"[ˈʃpaːniən]"},
{es:"Italia",de:"Italien",article:"",emoji:"🇮🇹",pron:"[iˈtaːliən]"},
{es:"Turquía",de:"die Türkei",article:"die",emoji:"🇹🇷",pron:"[tʏrˈkaɪ]"},
{es:"Inglaterra",de:"England",article:"",emoji:"🇬🇧",pron:"[ˈɛŋlant]"},
{es:"Estados Unidos",de:"die USA",article:"die",emoji:"🇺🇸",pron:"[uːɛsˈaː]"},
{es:"Rusia",de:"Russland",article:"",emoji:"🇷🇺",pron:"[ˈrʊslant]"},
{es:"China",de:"China",article:"",emoji:"🇨🇳",pron:"[ˈçiːna]"},
{es:"Japón",de:"Japan",article:"",emoji:"🇯🇵",pron:"[jaˈpaːn]"},
{es:"Brasil",de:"Brasilien",article:"",emoji:"🇧🇷",pron:"[braˈziːliən]"},
{es:"México",de:"Mexiko",article:"",emoji:"🇲🇽",pron:"[ˈmɛksiko]"},
{es:"Chile",de:"Chile",article:"",emoji:"🇨🇱",pron:"[ˈtʃiːlə]"},
],
"Orientación 🧭":[
{es:"todo recto",de:"geradeaus",article:"",emoji:"⬆️",pron:"[ɡəˈraːdəaʊs]"},
{es:"a la izquierda",de:"links",article:"",emoji:"⬅️",pron:"[lɪŋks]"},
{es:"a la derecha",de:"rechts",article:"",emoji:"➡️",pron:"[rɛçts]"},
{es:"el cruce",de:"die Kreuzung",article:"die",emoji:"✖️",pron:"[ˈkrɔʏtsʊŋ]"},
{es:"el semáforo",de:"die Ampel",article:"die",emoji:"🚦",pron:"[ˈampl̩]"},
{es:"la esquina",de:"die Ecke",article:"die",emoji:"📐",pron:"[ˈɛkə]"},
{es:"la calle",de:"die Straße",article:"die",emoji:"🛣️",pron:"[ˈʃtraːsə]"},
{es:"el puente",de:"die Brücke",article:"die",emoji:"🌉",pron:"[ˈbrʏkə]"},
{es:"enfrente de",de:"gegenüber",article:"",emoji:"↔️",pron:"[ˈɡeːɡn̩yːbɐ]"},
{es:"cerca",de:"in der Nähe",article:"",emoji:"📍",pron:""},
{es:"lejos",de:"weit",article:"",emoji:"🏔️",pron:"[vaɪt]"},
{es:"girar",de:"abbiegen",article:"",emoji:"↩️",pron:"[ˈapbiːɡn̩]"},
],
"Hobbys 🎨":[
{es:"jugar al fútbol",de:"Fußball spielen",article:"",emoji:"⚽",pron:""},
{es:"leer",de:"lesen",article:"",emoji:"📖",pron:"[ˈleːzn̩]"},
{es:"nadar",de:"schwimmen",article:"",emoji:"🏊",pron:"[ˈʃvɪmən]"},
{es:"ir de paseo",de:"spazieren gehen",article:"",emoji:"🚶",pron:""},
{es:"escuchar música",de:"Musik hören",article:"",emoji:"🎵",pron:""},
{es:"ver la tele",de:"fernsehen",article:"",emoji:"📺",pron:"[ˈfɛrnzeːən]"},
{es:"ir en bici",de:"Rad fahren",article:"",emoji:"🚴",pron:""},
{es:"fotografiar",de:"fotografieren",article:"",emoji:"📸",pron:"[fotoɡraˈfiːrən]"},
{es:"bailar",de:"tanzen",article:"",emoji:"💃",pron:"[ˈtantsn̩]"},
{es:"cantar",de:"singen",article:"",emoji:"🎤",pron:"[ˈzɪŋən]"},
{es:"ir al cine",de:"ins Kino gehen",article:"",emoji:"🎬",pron:""},
{es:"ir al teatro",de:"ins Theater gehen",article:"",emoji:"🎭",pron:""},
{es:"hacer deporte",de:"Sport machen",article:"",emoji:"🏃",pron:""},
{es:"cocinar",de:"kochen",article:"",emoji:"👨‍🍳",pron:"[ˈkɔxn̩]"},
{es:"viajar",de:"reisen",article:"",emoji:"✈️",pron:"[ˈraɪzn̩]"},
],
"Correos y banco 🏦":[
{es:"la carta",de:"der Brief",article:"der",emoji:"✉️",pron:"[briːf]"},
{es:"el sello",de:"die Briefmarke",article:"die",emoji:"📮",pron:"[ˈbriːfmarkə]"},
{es:"el paquete",de:"das Paket",article:"das",emoji:"📦",pron:"[paˈkeːt]"},
{es:"el remitente",de:"der Absender",article:"der",emoji:"📤",pron:"[ˈapzɛndɐ]"},
{es:"el destinatario",de:"der Empfänger",article:"der",emoji:"📥",pron:"[ɛmˈpfɛŋɐ]"},
{es:"el código postal",de:"die Postleitzahl",article:"die",emoji:"📬",pron:""},
{es:"el teléfono móvil",de:"das Handy",article:"das",emoji:"📱",pron:"[ˈhɛndi]"},
{es:"la cuenta",de:"das Konto",article:"das",emoji:"🏦",pron:"[ˈkɔnto]"},
{es:"transferir",de:"überweisen",article:"",emoji:"💸",pron:"[yːbɐˈvaɪzn̩]"},
{es:"la tarjeta de crédito",de:"die Kreditkarte",article:"die",emoji:"💳",pron:""},
{es:"el cajero automático",de:"der Geldautomat",article:"der",emoji:"🏧",pron:""},
{es:"pagar en efectivo",de:"bar zahlen",article:"",emoji:"💵",pron:""},
{es:"el carné/DNI",de:"der Ausweis",article:"der",emoji:"🪪",pron:"[ˈaʊsvaɪs]"},
{es:"la firma",de:"die Unterschrift",article:"die",emoji:"✍️",pron:"[ˈʊntɐʃrɪft]"},
],
"Escuela 🏫":[
{es:"la pizarra",de:"die Tafel",article:"die",emoji:"📋",pron:"[ˈtaːfl̩]"},
{es:"el cuaderno",de:"das Heft",article:"das",emoji:"📓",pron:"[hɛft]"},
{es:"el libro",de:"das Buch",article:"das",emoji:"📕",pron:"[buːx]"},
{es:"el lápiz",de:"der Bleistift",article:"der",emoji:"✏️",pron:"[ˈblaɪʃtɪft]"},
{es:"el bolígrafo",de:"der Kugelschreiber",article:"der",emoji:"🖊️",pron:""},
{es:"la clase",de:"die Klasse",article:"die",emoji:"🏫",pron:"[ˈklasə]"},
{es:"el examen",de:"die Prüfung",article:"die",emoji:"📝",pron:"[ˈpryːfʊŋ]"},
{es:"la tarea",de:"die Hausaufgabe",article:"die",emoji:"📚",pron:"[ˈhaʊsaʊfɡaːbə]"},
{es:"el ejercicio",de:"die Übung",article:"die",emoji:"✅",pron:"[ˈyːbʊŋ]"},
{es:"la pausa",de:"die Pause",article:"die",emoji:"☕",pron:"[ˈpaʊzə]"},
{es:"correcto",de:"richtig",article:"",emoji:"✅",pron:"[ˈrɪçtɪç]"},
{es:"incorrecto",de:"falsch",article:"",emoji:"❌",pron:"[falʃ]"},
{es:"fácil",de:"leicht",article:"",emoji:"😊",pron:"[laɪçt]"},
{es:"difícil",de:"schwer",article:"",emoji:"😰",pron:"[ʃveːɐ̯]"},
{es:"el curso de alemán",de:"der Deutschkurs",article:"der",emoji:"🇩🇪",pron:""},
],
"Objetos 🔑":[
{es:"las gafas",de:"die Brille",article:"die",emoji:"👓",pron:"[ˈbrɪlə]"},
{es:"la llave",de:"der Schlüssel",article:"der",emoji:"🔑",pron:"[ˈʃlʏsl̩]"},
{es:"el paraguas",de:"der Regenschirm",article:"der",emoji:"☂️",pron:"[ˈreːɡn̩ʃɪrm]"},
{es:"el bolso",de:"die Tasche",article:"die",emoji:"👜",pron:"[ˈtaʃə]"},
{es:"la botella",de:"die Flasche",article:"die",emoji:"🍾",pron:"[ˈflaʃə]"},
{es:"el collar",de:"die Kette",article:"die",emoji:"📿",pron:"[ˈkɛtə]"},
{es:"el encendedor",de:"das Feuerzeug",article:"das",emoji:"🔥",pron:"[ˈfɔʏɐtsɔʏk]"},
{es:"la cámara",de:"der Fotoapparat",article:"der",emoji:"📷",pron:"[ˈfoːtoaparaːt]"},
{es:"el monedero",de:"die Geldbörse",article:"die",emoji:"👛",pron:"[ˈɡɛltbœrzə]"},
{es:"el reloj (pulsera)",de:"die Uhr",article:"die",emoji:"⌚",pron:"[uːɐ̯]"},
{es:"la impresora",de:"der Drucker",article:"der",emoji:"🖨️",pron:"[ˈdrʊkɐ]"},
{es:"la pantalla",de:"der Bildschirm",article:"der",emoji:"🖥️",pron:"[ˈbɪltʃɪrm]"},
{es:"el calendario",de:"der Kalender",article:"der",emoji:"📅",pron:"[kaˈlɛndɐ]"},
{es:"el cuaderno de notas",de:"das Notizbuch",article:"das",emoji:"📔",pron:"[noˈtiːtsbuːx]"},
{es:"la factura",de:"die Rechnung",article:"die",emoji:"🧾",pron:"[ˈrɛçnʊŋ]"},
],
"Materiales 🧱":[
{es:"la madera",de:"das Holz",article:"das",emoji:"🪵",pron:"[hɔlts]"},
{es:"el metal",de:"das Metall",article:"das",emoji:"⚙️",pron:"[meˈtal]"},
{es:"el plástico",de:"das Plastik",article:"das",emoji:"♻️",pron:"[ˈplastɪk]"},
{es:"el vidrio",de:"das Glas",article:"das",emoji:"🪟",pron:"[ɡlaːs]"},
{es:"el papel",de:"das Papier",article:"das",emoji:"📄",pron:"[paˈpiːɐ̯]"},
{es:"el cuero",de:"das Leder",article:"das",emoji:"👞",pron:"[ˈleːdɐ]"},
{es:"redondo",de:"rund",article:"",emoji:"⭕",pron:"[rʊnt]"},
{es:"cuadrado",de:"eckig",article:"",emoji:"⬜",pron:"[ˈɛkɪç]"},
{es:"práctico",de:"praktisch",article:"",emoji:"👍",pron:"[ˈpraktɪʃ]"},
{es:"oferta especial",de:"das Sonderangebot",article:"das",emoji:"🏷️",pron:"[ˈzɔndɐanɡəboːt]"},
],
"Ocio y lugares 🎪":[
{es:"la piscina",de:"das Schwimmbad",article:"das",emoji:"🏊",pron:"[ˈʃvɪmbaːt]"},
{es:"el cine",de:"das Kino",article:"das",emoji:"🎬",pron:"[ˈkiːno]"},
{es:"la discoteca",de:"die Disco",article:"die",emoji:"🪩",pron:"[ˈdɪsko]"},
{es:"el teatro",de:"das Theater",article:"das",emoji:"🎭",pron:"[teˈaːtɐ]"},
{es:"el concierto",de:"das Konzert",article:"das",emoji:"🎵",pron:"[kɔnˈtsɛrt]"},
{es:"el bar",de:"die Bar",article:"die",emoji:"🍸",pron:"[baːɐ̯]"},
{es:"el museo",de:"das Museum",article:"das",emoji:"🏛️",pron:"[muˈzeːʊm]"},
{es:"el restaurante",de:"das Restaurant",article:"das",emoji:"🍽️",pron:"[rɛstoˈrɑ̃ː]"},
{es:"el café",de:"das Café",article:"das",emoji:"☕",pron:"[kaˈfeː]"},
{es:"el parque",de:"der Park",article:"der",emoji:"🌳",pron:"[park]"},
{es:"la entrada (ticket)",de:"die Eintrittskarte",article:"die",emoji:"🎫",pron:""},
{es:"la entrada de cine",de:"die Kinokarte",article:"die",emoji:"🎟️",pron:"[ˈkiːnokartə]"},
],
"Partes del día 🌅":[
{es:"la mañana",de:"der Morgen",article:"der",emoji:"🌅",pron:"[ˈmɔrɡn̩]"},
{es:"la mañana (antes mediodía)",de:"der Vormittag",article:"der",emoji:"🌤️",pron:"[ˈfoːɐ̯mɪtaːk]"},
{es:"el mediodía",de:"der Mittag",article:"der",emoji:"☀️",pron:"[ˈmɪtaːk]"},
{es:"la tarde",de:"der Nachmittag",article:"der",emoji:"🌇",pron:"[ˈnaːxmɪtaːk]"},
{es:"la noche (tarde)",de:"der Abend",article:"der",emoji:"🌙",pron:"[ˈaːbn̩t]"},
{es:"la noche (madrugada)",de:"die Nacht",article:"die",emoji:"🌑",pron:"[naxt]"},
{es:"hoy",de:"heute",article:"",emoji:"📅",pron:"[ˈhɔʏtə]"},
{es:"mañana",de:"morgen",article:"",emoji:"📅",pron:"[ˈmɔrɡn̩]"},
{es:"ayer",de:"gestern",article:"",emoji:"📅",pron:"[ˈɡɛstɐn]"},
{es:"ahora",de:"jetzt",article:"",emoji:"⏰",pron:"[jɛtst]"},
{es:"pronto",de:"bald",article:"",emoji:"⏳",pron:"[balt]"},
{es:"tarde (hora)",de:"spät",article:"",emoji:"🕐",pron:"[ʃpɛːt]"},
],
"Tareas del hogar 🧹":[
{es:"ordenar/recoger",de:"aufräumen",article:"",emoji:"🧹",pron:"[ˈaʊfʁɔʏmən]"},
{es:"limpiar",de:"putzen",article:"",emoji:"🧽",pron:"[ˈpʊtsn̩]"},
{es:"lavar (ropa)",de:"waschen",article:"",emoji:"👕",pron:"[ˈvaʃn̩]"},
{es:"fregar (platos)",de:"spülen",article:"",emoji:"🍽️",pron:"[ˈʃpyːlən]"},
{es:"cocinar",de:"kochen",article:"",emoji:"🍳",pron:"[ˈkɔxn̩]"},
{es:"barrer",de:"fegen",article:"",emoji:"🧹",pron:"[ˈfeːɡn̩]"},
{es:"pasar la aspiradora",de:"staubsaugen",article:"",emoji:"🧹",pron:"[ˈʃtaʊpzaʊɡn̩]"},
{es:"planchar",de:"bügeln",article:"",emoji:"👔",pron:"[ˈbyːɡl̩n]"},
{es:"la basura",de:"der Müll",article:"der",emoji:"🗑️",pron:"[mʏl]"},
{es:"la lavadora",de:"die Waschmaschine",article:"die",emoji:"🫧",pron:"[ˈvaʃmaʃiːnə]"},
{es:"el lavavajillas",de:"die Spülmaschine",article:"die",emoji:"🍽️",pron:"[ˈʃpyːlmaʃiːnə]"},
{es:"la escoba",de:"der Besen",article:"der",emoji:"🧹",pron:"[ˈbeːzn̩]"},
],
"Reglas y señales 🚫":[
{es:"permitido",de:"erlaubt",article:"",emoji:"✅",pron:"[ɛɐ̯ˈlaʊpt]"},
{es:"prohibido",de:"verboten",article:"",emoji:"🚫",pron:"[fɛɐ̯ˈboːtn̩]"},
{es:"tener que",de:"müssen",article:"",emoji:"⚠️",pron:"[ˈmʏsn̩]"},
{es:"poder (permiso)",de:"dürfen",article:"",emoji:"👍",pron:"[ˈdʏrfn̩]"},
{es:"parar/detenerse",de:"stehen bleiben",article:"",emoji:"🛑",pron:""},
{es:"ir a pie",de:"zu Fuß gehen",article:"",emoji:"🚶",pron:""},
{es:"llevar casco",de:"einen Helm tragen",article:"",emoji:"⛑️",pron:""},
{es:"aparcar",de:"parken",article:"",emoji:"🅿️",pron:"[ˈparkn̩]"},
{es:"fumar",de:"rauchen",article:"",emoji:"🚬",pron:"[ˈraʊxn̩]"},
{es:"fotografiar",de:"fotografieren",article:"",emoji:"📸",pron:"[fotoɡraˈfiːrən]"},
{es:"la señal",de:"das Schild",article:"das",emoji:"🪧",pron:"[ʃɪlt]"},
{es:"peligroso",de:"gefährlich",article:"",emoji:"⚠️",pron:"[ɡəˈfɛːɐ̯lɪç]"},
],
"Medidas 📏":[
{es:"el kilo",de:"das Kilo",article:"das",emoji:"⚖️",pron:"[ˈkiːlo]"},
{es:"la libra (500g)",de:"das Pfund",article:"das",emoji:"⚖️",pron:"[pfʊnt]"},
{es:"el gramo",de:"das Gramm",article:"das",emoji:"⚖️",pron:"[ɡram]"},
{es:"el litro",de:"der Liter",article:"der",emoji:"🥛",pron:"[ˈliːtɐ]"},
{es:"la botella",de:"die Flasche",article:"die",emoji:"🍾",pron:"[ˈflaʃə]"},
{es:"el vaso/tarro",de:"das Glas",article:"das",emoji:"🫙",pron:"[ɡlaːs]"},
{es:"la lata",de:"die Dose",article:"die",emoji:"🥫",pron:"[ˈdoːzə]"},
{es:"el paquete",de:"die Packung",article:"die",emoji:"📦",pron:"[ˈpakʊŋ]"},
{es:"el vasito",de:"der Becher",article:"der",emoji:"🥤",pron:"[ˈbɛçɐ]"},
{es:"la caja (bebidas)",de:"der Kasten",article:"der",emoji:"📦",pron:"[ˈkastn̩]"},
{es:"el trozo",de:"das Stück",article:"das",emoji:"🍰",pron:"[ʃtʏk]"},
{es:"la porción",de:"die Portion",article:"die",emoji:"🍽️",pron:"[pɔrˈt͡si̯oːn]"},
],
"Vivienda 🏡":[
{es:"la vivienda",de:"die Wohnung",article:"die",emoji:"🏠",pron:"[ˈvoːnʊŋ]"},
{es:"el piso/planta",de:"der Stock",article:"der",emoji:"🏢",pron:"[ʃtɔk]"},
{es:"el ascensor",de:"der Aufzug",article:"der",emoji:"🛗",pron:"[ˈaʊftsuːk]"},
{es:"la dirección",de:"die Adresse",article:"die",emoji:"📬",pron:"[aˈdrɛsə]"},
{es:"el vecino",de:"der Nachbar",article:"der",emoji:"🏘️",pron:"[ˈnaxbaːɐ̯]"},
{es:"mudarse",de:"umziehen",article:"",emoji:"📦",pron:"[ˈʊmtsiːən]"},
{es:"alquilar",de:"mieten",article:"",emoji:"🔑",pron:"[ˈmiːtn̩]"},
{es:"el garaje",de:"die Garage",article:"die",emoji:"🅿️",pron:"[ɡaˈraːʒə]"},
{es:"el balcón",de:"der Balkon",article:"der",emoji:"🌿",pron:"[balˈkɔŋ]"},
{es:"la terraza",de:"die Terrasse",article:"die",emoji:"☀️",pron:"[tɛˈrasə]"},
{es:"la calefacción",de:"die Heizung",article:"die",emoji:"🔥",pron:"[ˈhaɪtsʊŋ]"},
],
"Verbos cotidianos 🔄":[
{es:"abrir",de:"öffnen",article:"",emoji:"🚪",pron:"[ˈœfnən]"},
{es:"cerrar",de:"schließen",article:"",emoji:"🔒",pron:"[ˈʃliːsn̩]"},
{es:"dar",de:"geben",article:"",emoji:"🤲",pron:"[ˈɡeːbn̩]"},
{es:"traer",de:"bringen",article:"",emoji:"📦",pron:"[ˈbrɪŋən]"},
{es:"llevar (puesto)",de:"tragen",article:"",emoji:"👕",pron:"[ˈtraːɡn̩]"},
{es:"llevar consigo",de:"mitnehmen",article:"",emoji:"🎒",pron:"[ˈmɪtneːmən]"},
{es:"esperar",de:"warten",article:"",emoji:"⏳",pron:"[ˈvartn̩]"},
{es:"creer",de:"glauben",article:"",emoji:"🤔",pron:"[ˈɡlaʊbn̩]"},
{es:"saber",de:"wissen",article:"",emoji:"🧠",pron:"[ˈvɪsn̩]"},
{es:"conocer",de:"kennen",article:"",emoji:"🤝",pron:"[ˈkɛnən]"},
{es:"ayudar",de:"helfen",article:"",emoji:"🆘",pron:"[ˈhɛlfn̩]"},
{es:"visitar",de:"besuchen",article:"",emoji:"🏠",pron:"[bəˈzuːxn̩]"},
{es:"mostrar",de:"zeigen",article:"",emoji:"👉",pron:"[ˈtsaɪɡn̩]"},
{es:"empezar",de:"anfangen",article:"",emoji:"▶️",pron:"[ˈanfaŋən]"},
{es:"terminar",de:"aufhören",article:"",emoji:"⏹️",pron:"[ˈaʊfhøːrən]"},
{es:"pagar",de:"bezahlen",article:"",emoji:"💰",pron:"[bəˈtsaːlən]"},
{es:"llamar (por tel.)",de:"anrufen",article:"",emoji:"📞",pron:"[ˈanruːfn̩]"},
{es:"enviar",de:"schicken",article:"",emoji:"📤",pron:"[ˈʃɪkn̩]"},
{es:"preguntar",de:"fragen",article:"",emoji:"❓",pron:"[ˈfraːɡn̩]"},
{es:"responder",de:"antworten",article:"",emoji:"💬",pron:"[ˈantvɔrtn̩]"},
],
"Adverbios y conectores 🔗":[
{es:"siempre",de:"immer",article:"",emoji:"♾️",pron:"[ˈɪmɐ]"},
{es:"a menudo",de:"oft",article:"",emoji:"🔄",pron:"[ɔft]"},
{es:"a veces",de:"manchmal",article:"",emoji:"🎲",pron:"[ˈmançmaːl]"},
{es:"nunca",de:"nie",article:"",emoji:"🚫",pron:"[niː]"},
{es:"ya",de:"schon",article:"",emoji:"✅",pron:"[ʃoːn]"},
{es:"todavía",de:"noch",article:"",emoji:"⏳",pron:"[nɔx]"},
{es:"solo/solamente",de:"nur",article:"",emoji:"1️⃣",pron:"[nuːɐ̯]"},
{es:"también",de:"auch",article:"",emoji:"➕",pron:"[aʊx]"},
{es:"muy",de:"sehr",article:"",emoji:"💯",pron:"[zeːɐ̯]"},
{es:"quizás",de:"vielleicht",article:"",emoji:"🤷",pron:"[fiˈlaɪçt]"},
{es:"juntos",de:"zusammen",article:"",emoji:"🤝",pron:"[tsuˈzamən]"},
{es:"entonces/luego",de:"dann",article:"",emoji:"➡️",pron:"[dan]"},
{es:"primero",de:"zuerst",article:"",emoji:"1️⃣",pron:"[tsuˈeːɐ̯st]"},
{es:"después",de:"danach",article:"",emoji:"2️⃣",pron:"[daˈnaːx]"},
{es:"por fin/al final",de:"zum Schluss",article:"",emoji:"🏁",pron:""},
{es:"por desgracia",de:"leider",article:"",emoji:"😔",pron:"[ˈlaɪdɐ]"},
{es:"con mucho gusto",de:"gern(e)",article:"",emoji:"😊",pron:"[ɡɛrn]"},
{es:"enseguida",de:"gleich",article:"",emoji:"⚡",pron:"[ɡlaɪç]"},
{es:"exactamente",de:"genau",article:"",emoji:"🎯",pron:"[ɡəˈnaʊ]"},
{es:"realmente",de:"wirklich",article:"",emoji:"❗",pron:"[ˈvɪrklɪç]"},
],
"Más adjetivos 🏷️":[
{es:"joven",de:"jung",article:"",emoji:"👶",pron:"[jʊŋ]"},
{es:"contento",de:"froh",article:"",emoji:"😊",pron:"[froː]"},
{es:"triste",de:"traurig",article:"",emoji:"😢",pron:"[ˈtraʊrɪç]"},
{es:"cansado",de:"müde",article:"",emoji:"😴",pron:"[ˈmyːdə]"},
{es:"enfermo",de:"krank",article:"",emoji:"🤒",pron:"[kraŋk]"},
{es:"sano",de:"gesund",article:"",emoji:"💪",pron:"[ɡəˈzʊnt]"},
{es:"importante",de:"wichtig",article:"",emoji:"❗",pron:"[ˈvɪçtɪç]"},
{es:"tranquilo",de:"ruhig",article:"",emoji:"🤫",pron:"[ˈruːɪç]"},
{es:"ruidoso",de:"laut",article:"",emoji:"🔊",pron:"[laʊt]"},
{es:"bajo (sonido)",de:"leise",article:"",emoji:"🔉",pron:"[ˈlaɪzə]"},
{es:"posible",de:"möglich",article:"",emoji:"💡",pron:"[ˈmøːklɪç]"},
{es:"solo/a",de:"allein",article:"",emoji:"🧍",pron:"[aˈlaɪn]"},
{es:"casado/a",de:"verheiratet",article:"",emoji:"💍",pron:"[fɛɐ̯ˈhaɪraːtət]"},
{es:"soltero/a",de:"ledig",article:"",emoji:"🙋",pron:"[ˈleːdɪç]"},
{es:"puntual",de:"pünktlich",article:"",emoji:"⏰",pron:"[ˈpʏŋktlɪç]"},
{es:"conocido",de:"bekannt",article:"",emoji:"⭐",pron:"[bəˈkant]"},
{es:"extranjero",de:"ausländisch",article:"",emoji:"🌍",pron:"[ˈaʊslɛndɪʃ]"},
{es:"gratis",de:"kostenlos",article:"",emoji:"🆓",pron:"[ˈkɔstn̩loːs]"},
],
"Más sustantivos Goethe 📋":[
{es:"el problema",de:"das Problem",article:"das",emoji:"⚠️",pron:"[proˈbleːm]"},
{es:"la pregunta",de:"die Frage",article:"die",emoji:"❓",pron:"[ˈfraːɡə]"},
{es:"la respuesta",de:"die Antwort",article:"die",emoji:"💬",pron:"[ˈantvɔrt]"},
{es:"la idea",de:"die Idee",article:"die",emoji:"💡",pron:"[iˈdeː]"},
{es:"el ejemplo",de:"das Beispiel",article:"das",emoji:"📝",pron:"[ˈbaɪʃpiːl]"},
{es:"el regalo",de:"das Geschenk",article:"das",emoji:"🎁",pron:"[ɡəˈʃɛŋk]"},
{es:"la fiesta",de:"die Party",article:"die",emoji:"🎉",pron:"[ˈpaːrti]"},
{es:"el cumpleaños",de:"der Geburtstag",article:"der",emoji:"🎂",pron:"[ɡəˈbuːɐ̯tstaːk]"},
{es:"la invitación",de:"die Einladung",article:"die",emoji:"💌",pron:"[ˈaɪnlaːdʊŋ]"},
{es:"la cita/turno",de:"der Termin",article:"der",emoji:"📅",pron:"[tɛrˈmiːn]"},
{es:"el dinero",de:"das Geld",article:"das",emoji:"💶",pron:"[ɡɛlt]"},
{es:"la información",de:"die Information",article:"die",emoji:"ℹ️",pron:"[ɪnfɔrmaˈt͡si̯oːn]"},
{es:"el idioma",de:"die Sprache",article:"die",emoji:"🗣️",pron:"[ˈʃpraːxə]"},
{es:"la foto",de:"das Foto",article:"das",emoji:"📷",pron:"[ˈfoːto]"},
{es:"la suerte",de:"das Glück",article:"das",emoji:"🍀",pron:"[ɡlʏk]"},
{es:"la ayuda",de:"die Hilfe",article:"die",emoji:"🆘",pron:"[ˈhɪlfə]"},
{es:"el error",de:"der Fehler",article:"der",emoji:"❌",pron:"[ˈfeːlɐ]"},
{es:"el lugar",de:"der Ort",article:"der",emoji:"📍",pron:"[ɔrt]"},
{es:"el tiempo libre",de:"die Freizeit",article:"die",emoji:"🎮",pron:"[ˈfraɪtsaɪt]"},
{es:"el periódico",de:"die Zeitung",article:"die",emoji:"📰",pron:"[ˈtsaɪtʊŋ]"},
],
"Palabras funcionales ⚙️":[
{es:"todo/todos",de:"alle",article:"",emoji:"👥",pron:"[ˈalə]"},
{es:"todo (neutro)",de:"alles",article:"",emoji:"💯",pron:"[ˈaləs]"},
{es:"otro/a",de:"andere",article:"",emoji:"↔️",pron:"[ˈandərə]"},
{es:"cada",de:"jeder/jede/jedes",article:"",emoji:"🔢",pron:"[ˈjeːdɐ]"},
{es:"mucho",de:"viel",article:"",emoji:"📈",pron:"[fiːl]"},
{es:"poco",de:"wenig",article:"",emoji:"📉",pron:"[ˈveːnɪç]"},
{es:"más",de:"mehr",article:"",emoji:"➕",pron:"[meːɐ̯]"},
{es:"bastante",de:"genug",article:"",emoji:"✅",pron:"[ɡəˈnuːk]"},
{es:"nada",de:"nichts",article:"",emoji:"0️⃣",pron:"[nɪçts]"},
{es:"algo",de:"etwas",article:"",emoji:"🤏",pron:"[ˈɛtvas]"},
{es:"alguien",de:"jemand",article:"",emoji:"🧑",pron:"[ˈjeːmant]"},
{es:"nadie",de:"niemand",article:"",emoji:"🚷",pron:"[ˈniːmant]"},
{es:"aquí",de:"hier",article:"",emoji:"📍",pron:"[hiːɐ̯]"},
{es:"allí",de:"dort",article:"",emoji:"👉",pron:"[dɔrt]"},
{es:"arriba",de:"oben",article:"",emoji:"⬆️",pron:"[ˈoːbn̩]"},
{es:"abajo",de:"unten",article:"",emoji:"⬇️",pron:"[ˈʊntn̩]"},
{es:"fuera",de:"draußen",article:"",emoji:"🌳",pron:"[ˈdraʊsn̩]"},
{es:"pero",de:"aber",article:"",emoji:"↩️",pron:"[ˈaːbɐ]"},
{es:"porque",de:"weil",article:"",emoji:"💡",pron:"[vaɪl]"},
{es:"que (conj.)",de:"dass",article:"",emoji:"💬",pron:"[das]"},
{es:"cuando/si",de:"wenn",article:"",emoji:"🔀",pron:"[vɛn]"},
{es:"o",de:"oder",article:"",emoji:"🔄",pron:"[ˈoːdɐ]"},
{es:"y",de:"und",article:"",emoji:"➕",pron:"[ʊnt]"},
],
"Expresiones del examen 📝":[
{es:"marcar con una X",de:"ankreuzen",article:"",emoji:"✖️",pron:"[ˈankrɔʏtsn̩]"},
{es:"completar",de:"ergänzen",article:"",emoji:"✏️",pron:"[ɛɐ̯ˈɡɛntsn̩]"},
{es:"relacionar",de:"zuordnen",article:"",emoji:"🔗",pron:"[ˈtsuːɔrdnən]"},
{es:"la solución",de:"die Lösung",article:"die",emoji:"✅",pron:"[ˈløːzʊŋ]"},
{es:"el formulario",de:"das Formular",article:"das",emoji:"📋",pron:"[fɔrmuˈlaːɐ̯]"},
{es:"rellenar",de:"ausfüllen",article:"",emoji:"✍️",pron:"[ˈaʊsfʏlən]"},
{es:"firmar",de:"unterschreiben",article:"",emoji:"🖊️",pron:"[ˈʊntɐʃraɪbn̩]"},
{es:"deletrear",de:"buchstabieren",article:"",emoji:"🔤",pron:"[buːxʃtaˈbiːrən]"},
{es:"la frase",de:"der Satz",article:"der",emoji:"📝",pron:"[zats]"},
{es:"la palabra",de:"das Wort",article:"das",emoji:"💬",pron:"[vɔrt]"},
{es:"el texto",de:"der Text",article:"der",emoji:"📄",pron:"[tɛkst]"},
{es:"la oración",de:"der Satz",article:"der",emoji:"📝",pron:"[zats]"},
{es:"repetir",de:"wiederholen",article:"",emoji:"🔁",pron:"[ˈviːdɐhoːlən]"},
{es:"entender",de:"verstehen",article:"",emoji:"🧠",pron:"[fɛɐ̯ˈʃteːən]"},
{es:"explicar",de:"erklären",article:"",emoji:"💡",pron:"[ɛɐ̯ˈklɛːrən]"},
{es:"pronunciar",de:"aussprechen",article:"",emoji:"🗣️",pron:"[ˈaʊsʃprɛçn̩]"},
],
"Vida cotidiana 🏙️":[
{es:"la gente",de:"die Leute",article:"die",emoji:"👥",pron:"[ˈlɔʏtə]"},
{es:"la persona",de:"die Person",article:"die",emoji:"🧑",pron:"[pɛrˈzoːn]"},
{es:"la vida",de:"das Leben",article:"das",emoji:"🌱",pron:"[ˈleːbn̩]"},
{es:"el mundo",de:"die Welt",article:"die",emoji:"🌍",pron:"[vɛlt]"},
{es:"la ciudad",de:"die Stadt",article:"die",emoji:"🏙️",pron:"[ʃtat]"},
{es:"el campo",de:"das Land",article:"das",emoji:"🌾",pron:"[lant]"},
{es:"el pueblo",de:"das Dorf",article:"das",emoji:"🏘️",pron:"[dɔrf]"},
{es:"la flor",de:"die Blume",article:"die",emoji:"🌸",pron:"[ˈbluːmə]"},
{es:"el árbol",de:"der Baum",article:"der",emoji:"🌳",pron:"[baʊm]"},
{es:"el animal",de:"das Tier",article:"das",emoji:"🐾",pron:"[tiːɐ̯]"},
{es:"la iglesia",de:"die Kirche",article:"die",emoji:"⛪",pron:"[ˈkɪrçə]"},
{es:"la plaza",de:"der Platz",article:"der",emoji:"🏛️",pron:"[plats]"},
{es:"la farmacia",de:"die Apotheke",article:"die",emoji:"💊",pron:"[apoˈteːkə]"},
{es:"la policía",de:"die Polizei",article:"die",emoji:"👮",pron:"[poliˈtsaɪ]"},
{es:"el supermercado",de:"der Supermarkt",article:"der",emoji:"🛒",pron:"[ˈzuːpɐmarkt]"},
{es:"la tienda",de:"das Geschäft",article:"das",emoji:"🏪",pron:"[ɡəˈʃɛft]"},
{es:"el mercado",de:"der Markt",article:"der",emoji:"🧺",pron:"[markt]"},
{es:"la panadería",de:"die Bäckerei",article:"die",emoji:"🥖",pron:"[bɛkəˈraɪ]"},
{es:"la carnicería",de:"die Metzgerei",article:"die",emoji:"🥩",pron:"[mɛtsɡəˈraɪ]"},
{es:"el banco (inst.)",de:"die Bank",article:"die",emoji:"🏦",pron:"[baŋk]"},
],
};

// A1 READINGS
const READINGS_A1 = [
{id:"intro",icon:"👋",title:"Sich vorstellen",desc:"Presentarse en alemán",level:"A1",
lines:[
{de:"Hallo! Ich heiße Maria.",es:"¡Hola! Me llamo María."},
{de:"Ich komme aus Chile und wohne jetzt in Berlin.",es:"Vengo de Chile y ahora vivo en Berlín."},
{de:"Ich bin dreiundzwanzig Jahre alt.",es:"Tengo veintitrés años."},
{de:"Ich spreche Spanisch und ein bisschen Deutsch.",es:"Hablo español y un poco de alemán."},
{de:"Ich lerne Deutsch, denn ich arbeite in Deutschland.",es:"Aprendo alemán porque trabajo en Alemania."},
{de:"Meine Hobbys sind Musik hören und kochen.",es:"Mis hobbies son escuchar música y cocinar."},
{de:"Ich habe eine Schwester. Sie heißt Ana.",es:"Tengo una hermana. Se llama Ana."},
{de:"Freut mich! Und wie heißt du?",es:"¡Encantada! ¿Y tú cómo te llamas?"},
],quiz:[
{q:"¿De dónde viene María?",opts:["Deutschland","Spanien","Chile","Berlin"],correct:2},
{q:"¿Cuántos años tiene?",opts:["22","23","24","25"],correct:1},
{q:"¿Por qué aprende alemán?",opts:["Por diversión","Porque tiene familia","Porque trabaja en Alemania","Para viajar"],correct:2},
{q:"¿Cómo se llama su hermana?",opts:["María","Paula","Ana","Lisa"],correct:2},
]},
{id:"alltag",icon:"🌅",title:"Mein Tag",desc:"Un día normal en la vida de Thomas",level:"A1",
lines:[
{de:"Ich stehe jeden Tag um sieben Uhr auf.",es:"Me levanto cada día a las siete."},
{de:"Zuerst dusche ich und dann frühstücke ich.",es:"Primero me ducho y después desayuno."},
{de:"Ich trinke immer Kaffee mit Milch und esse Brot mit Käse.",es:"Siempre bebo café con leche y como pan con queso."},
{de:"Um halb neun fahre ich mit dem Bus zur Arbeit.",es:"A las ocho y media voy en autobús al trabajo."},
{de:"Ich arbeite von neun bis fünf Uhr.",es:"Trabajo de nueve a cinco."},
{de:"In der Mittagspause esse ich oft einen Salat.",es:"En la pausa del almuerzo como a menudo una ensalada."},
{de:"Nach der Arbeit gehe ich manchmal ins Fitnessstudio.",es:"Después del trabajo a veces voy al gimnasio."},
{de:"Am Abend koche ich und sehe ein bisschen fern.",es:"Por la noche cocino y veo un poco la tele."},
{de:"Um elf Uhr gehe ich schlafen. Gute Nacht!",es:"A las once me voy a dormir. ¡Buenas noches!"},
],quiz:[
{q:"¿A qué hora se levanta Thomas?",opts:["Um sechs","Um sieben","Um acht","Um neun"],correct:1},
{q:"¿Qué come al desayuno?",opts:["Müsli","Obst","Brot mit Käse","Eier"],correct:2},
{q:"¿Cómo va al trabajo?",opts:["Mit dem Auto","Mit dem Fahrrad","Zu Fuß","Mit dem Bus"],correct:3},
{q:"¿Qué hace después del trabajo?",opts:["Lesen","Manchmal Fitnessstudio","Schwimmen","Einkaufen"],correct:1},
]},
{id:"wohnung",icon:"🏠",title:"Meine Wohnung",desc:"Lisa describe su apartamento",level:"A1",
lines:[
{de:"Ich wohne in einer kleinen Wohnung in Hamburg.",es:"Vivo en un apartamento pequeño en Hamburgo."},
{de:"Die Wohnung hat drei Zimmer: ein Schlafzimmer, ein Wohnzimmer und eine Küche.",es:"El apartamento tiene tres habitaciones: un dormitorio, un salón y una cocina."},
{de:"Das Badezimmer ist klein, aber es hat eine Dusche.",es:"El baño es pequeño, pero tiene una ducha."},
{de:"Im Wohnzimmer stehen ein Sofa, ein Tisch und ein Fernseher.",es:"En el salón hay un sofá, una mesa y una televisión."},
{de:"Ich habe auch einen kleinen Balkon. Dort trinke ich morgens meinen Kaffee.",es:"También tengo un balcón pequeño. Allí bebo mi café por las mañanas."},
{de:"Die Miete ist sechshundert Euro im Monat.",es:"El alquiler es de seiscientos euros al mes."},
{de:"Meine Nachbarn sind sehr nett.",es:"Mis vecinos son muy amables."},
{de:"Ich mag meine Wohnung. Sie ist gemütlich.",es:"Me gusta mi apartamento. Es acogedor."},
],quiz:[
{q:"¿Dónde vive Lisa?",opts:["Berlin","München","Hamburg","Köln"],correct:2},
{q:"¿Cuántas habitaciones tiene la Wohnung?",opts:["Zwei","Drei","Vier","Fünf"],correct:1},
{q:"¿Qué hace Lisa en el balcón?",opts:["Lesen","Kaffee trinken","Sport machen","Schlafen"],correct:1},
{q:"¿Cuánto cuesta la Miete?",opts:["400 Euro","500 Euro","600 Euro","700 Euro"],correct:2},
]},
{id:"restaurant",icon:"🍽️",title:"Im Restaurant",desc:"Diálogo real pidiendo comida",level:"A1",
lines:[
{de:"Kellner: Guten Abend! Haben Sie reserviert?",es:"Camarero: ¡Buenas noches! ¿Tienen reserva?"},
{de:"Gast: Ja, auf den Namen Schmidt, für zwei Personen.",es:"Cliente: Sí, a nombre de Schmidt, para dos personas."},
{de:"Kellner: Natürlich, kommen Sie bitte mit. Hier ist Ihr Tisch.",es:"Camarero: Por supuesto, vengan conmigo. Aquí está su mesa."},
{de:"Kellner: Möchten Sie schon etwas trinken?",es:"Camarero: ¿Quieren algo de beber?"},
{de:"Gast: Ich hätte gerne ein Glas Weißwein, bitte.",es:"Cliente: Me gustaría una copa de vino blanco, por favor."},
{de:"Gast: Und für meine Frau ein Wasser ohne Kohlensäure.",es:"Cliente: Y para mi mujer un agua sin gas."},
{de:"Kellner: Möchten Sie auch schon bestellen?",es:"Camarero: ¿Quieren pedir también ya?"},
{de:"Gast: Ja, ich nehme das Hähnchen mit Reis, bitte.",es:"Cliente: Sí, yo pido el pollo con arroz, por favor."},
{de:"Gast: Und meine Frau hätte gerne den Fisch mit Kartoffeln.",es:"Cliente: Y mi mujer quiere el pescado con patatas."},
{de:"Kellner: Sehr gern! Guten Appetit!",es:"Camarero: ¡Con mucho gusto! ¡Buen provecho!"},
{de:"Gast: Die Rechnung, bitte. Es hat sehr gut geschmeckt!",es:"Cliente: La cuenta, por favor. ¡Estaba muy rico!"},
],quiz:[
{q:"¿A nombre de quién es la reserva?",opts:["Müller","Weber","Schmidt","Fischer"],correct:2},
{q:"¿Qué bebe el señor?",opts:["Bier","Rotwein","Wasser","Weißwein"],correct:3},
{q:"¿Qué pide el señor para comer?",opts:["Fisch mit Kartoffeln","Hähnchen mit Reis","Steak mit Salat","Pizza"],correct:1},
{q:"¿Qué dice el camarero al servir?",opts:["Tschüss!","Danke schön!","Guten Appetit!","Auf Wiedersehen!"],correct:2},
]},
{id:"einkaufen",icon:"🛒",title:"Auf dem Markt",desc:"Comprando en el mercado",level:"A1",
lines:[
{de:"Verkäufer: Guten Morgen! Was darf es sein?",es:"Vendedor: ¡Buenos días! ¿Qué le pongo?"},
{de:"Kundin: Guten Morgen! Ich hätte gerne ein Kilo Äpfel.",es:"Clienta: ¡Buenos días! Me gustaría un kilo de manzanas."},
{de:"Verkäufer: Die roten oder die grünen?",es:"Vendedor: ¿Las rojas o las verdes?"},
{de:"Kundin: Die roten, bitte. Was kosten die Tomaten?",es:"Clienta: Las rojas, por favor. ¿Cuánto cuestan los tomates?"},
{de:"Verkäufer: Zwei Euro das Kilo.",es:"Vendedor: Dos euros el kilo."},
{de:"Kundin: Dann nehme ich auch ein halbes Kilo Tomaten.",es:"Clienta: Entonces también un medio kilo de tomates."},
{de:"Kundin: Und noch drei Bananen, bitte.",es:"Clienta: Y tres plátanos más, por favor."},
{de:"Verkäufer: Sonst noch etwas?",es:"Vendedor: ¿Algo más?"},
{de:"Kundin: Nein, danke. Das ist alles. Was macht das zusammen?",es:"Clienta: No, gracias. Eso es todo. ¿Cuánto es en total?"},
{de:"Verkäufer: Das macht fünf Euro fünfzig. Vielen Dank!",es:"Vendedor: Son cinco euros cincuenta. ¡Muchas gracias!"},
],quiz:[
{q:"¿Qué compra primero la clienta?",opts:["Tomaten","Bananen","Äpfel","Kartoffeln"],correct:2},
{q:"¿Cuánto cuestan los Tomaten?",opts:["1 Euro","2 Euro","3 Euro","5 Euro"],correct:1},
{q:"'Sonst noch etwas?' significa...",opts:["¿Cuánto cuesta?","¿Algo más?","¿Efectivo o tarjeta?","¿Es todo?"],correct:1},
{q:"¿Cuánto paga en total?",opts:["4,50 €","5,00 €","5,50 €","6,00 €"],correct:2},
]},
{id:"arzt",icon:"🏥",title:"Beim Arzt",desc:"Visita al médico",level:"A1",
lines:[
{de:"Ärztin: Guten Tag, Herr Müller. Was fehlt Ihnen?",es:"Doctora: Buenos días, señor Müller. ¿Qué le pasa?"},
{de:"Patient: Guten Tag. Ich habe seit zwei Tagen Kopfschmerzen.",es:"Paciente: Buenos días. Tengo dolor de cabeza desde hace dos días."},
{de:"Patient: Und mein Hals tut auch weh.",es:"Paciente: Y también me duele la garganta."},
{de:"Ärztin: Haben Sie auch Fieber?",es:"Doctora: ¿Tiene también fiebre?"},
{de:"Patient: Ja, ich glaube, ein bisschen.",es:"Paciente: Sí, creo que un poco."},
{de:"Ärztin: Öffnen Sie bitte den Mund. Sagen Sie bitte 'Aaa'.",es:"Doctora: Abra la boca, por favor. Diga 'Aaa'."},
{de:"Ärztin: Sie haben eine Erkältung. Nichts Schlimmes.",es:"Doctora: Tiene un resfriado. Nada grave."},
{de:"Ärztin: Sie müssen viel Tee trinken und im Bett bleiben.",es:"Doctora: Tiene que beber mucho té y quedarse en la cama."},
{de:"Ärztin: Ich schreibe Ihnen ein Rezept für die Apotheke.",es:"Doctora: Le escribo una receta para la farmacia."},
{de:"Patient: Vielen Dank, Frau Doktor. Auf Wiedersehen!",es:"Paciente: ¡Muchas gracias, doctora! ¡Hasta luego!"},
],quiz:[
{q:"¿Qué le duele al señor Müller?",opts:["Bauch und Bein","Kopf und Hals","Arm und Hand","Rücken und Fuß"],correct:1},
{q:"¿Tiene fiebre?",opts:["Nein","Ja, ein bisschen","Ja, sehr hoch","Er weiß nicht"],correct:1},
{q:"¿Qué diagnóstico da la doctora?",opts:["Grippe","Allergie","Erkältung","Verletzung"],correct:2},
{q:"¿Qué debe hacer el paciente?",opts:["Sport machen","Arbeiten gehen","Tee trinken und im Bett bleiben","Ins Krankenhaus gehen"],correct:2},
]},
{id:"reise",icon:"🚆",title:"Eine Zugfahrt",desc:"Viaje en tren por Alemania",level:"A1",
lines:[
{de:"Am Schalter: Eine Fahrkarte nach München, bitte.",es:"En el mostrador: Un billete a Múnich, por favor."},
{de:"Einfach oder hin und zurück?",es:"¿Solo ida o ida y vuelta?"},
{de:"Hin und zurück, bitte. Wann fährt der nächste Zug?",es:"Ida y vuelta, por favor. ¿Cuándo sale el próximo tren?"},
{de:"Der nächste Zug fährt um vierzehn Uhr dreißig von Gleis sieben.",es:"El próximo tren sale a las catorce treinta del andén siete."},
{de:"Muss ich umsteigen?",es:"¿Tengo que hacer trasbordo?"},
{de:"Ja, einmal in Nürnberg. Sie haben dort zwanzig Minuten.",es:"Sí, una vez en Núremberg. Tiene allí veinte minutos."},
{de:"Was kostet die Fahrkarte?",es:"¿Cuánto cuesta el billete?"},
{de:"Neunundfünfzig Euro. Erste oder zweite Klasse?",es:"Cincuenta y nueve euros. ¿Primera o segunda clase?"},
{de:"Zweite Klasse, bitte. Kann ich mit Karte zahlen?",es:"Segunda clase, por favor. ¿Puedo pagar con tarjeta?"},
{de:"Ja, natürlich. Hier ist Ihre Fahrkarte. Gute Reise!",es:"Sí, por supuesto. Aquí tiene su billete. ¡Buen viaje!"},
],quiz:[
{q:"¿A dónde viaja?",opts:["Berlin","Hamburg","München","Köln"],correct:2},
{q:"¿Desde qué Gleis sale el tren?",opts:["Gleis 5","Gleis 7","Gleis 9","Gleis 12"],correct:1},
{q:"¿Dónde tiene que umsteigen?",opts:["Frankfurt","Stuttgart","Nürnberg","Hannover"],correct:2},
{q:"¿Cuánto cuesta la Fahrkarte?",opts:["49 €","59 €","69 €","79 €"],correct:1},
]},
];

const SENTENCES_A1 = [
{de:"Ich heiße Anna",es:"Me llamo Anna",hint:"presentarse"},
{de:"Wie geht es dir",es:"¿Cómo estás?",hint:"saludo"},
{de:"Ich komme aus Spanien",es:"Vengo de España",hint:"origen"},
{de:"Wo wohnst du",es:"¿Dónde vives?",hint:"vivienda"},
{de:"Ich wohne in Berlin",es:"Vivo en Berlín",hint:"vivienda"},
{de:"Ich spreche Deutsch",es:"Hablo alemán",hint:"idiomas"},
{de:"Das ist mein Bruder",es:"Este es mi hermano",hint:"familia"},
{de:"Meine Mutter heißt Maria",es:"Mi madre se llama María",hint:"familia"},
{de:"Ich habe zwei Kinder",es:"Tengo dos hijos",hint:"familia"},
{de:"Er trinkt einen Kaffee",es:"Él bebe un café",hint:"comida"},
{de:"Wir essen Brot zum Frühstück",es:"Comemos pan para el desayuno",hint:"comida"},
{de:"Ich möchte ein Wasser bitte",es:"Quisiera un agua por favor",hint:"pedir"},
{de:"Die Schule beginnt um acht Uhr",es:"La escuela comienza a las ocho",hint:"hora"},
{de:"Ich gehe jeden Tag zur Arbeit",es:"Voy al trabajo todos los días",hint:"rutina"},
{de:"Er liest ein Buch",es:"Él lee un libro",hint:"hobbys"},
{de:"Wir spielen gern Fußball",es:"Nos gusta jugar fútbol",hint:"hobbys"},
{de:"Das Wetter ist heute schön",es:"El clima está bonito hoy",hint:"clima"},
{de:"Es regnet seit gestern",es:"Llueve desde ayer",hint:"clima"},
{de:"Ich fahre mit dem Bus",es:"Voy en autobús",hint:"transporte"},
{de:"Der Zug kommt um drei Uhr",es:"El tren llega a las tres",hint:"transporte"},
{de:"Kannst du mir helfen",es:"¿Puedes ayudarme?",hint:"pedir ayuda"},
{de:"Wo ist der Bahnhof",es:"¿Dónde está la estación?",hint:"orientación"},
{de:"Ich verstehe das nicht",es:"No entiendo eso",hint:"supervivencia"},
{de:"Können Sie das wiederholen",es:"¿Puede repetir eso?",hint:"supervivencia"},
{de:"Ich kaufe Milch und Brot",es:"Compro leche y pan",hint:"compras"},
{de:"Wie viel kostet das",es:"¿Cuánto cuesta eso?",hint:"compras"},
{de:"Die Katze schläft auf dem Sofa",es:"El gato duerme en el sofá",hint:"animales"},
{de:"Ich muss heute arbeiten",es:"Tengo que trabajar hoy",hint:"obligación"},
{de:"Wir gehen morgen ins Kino",es:"Vamos mañana al cine",hint:"planes"},
{de:"Am Wochenende besuche ich Freunde",es:"El fin de semana visito amigos",hint:"planes"},
];

const VERBS_A1 = [
{inf:"sein",es:"ser/estar",type:"irregular",conj:{ich:"bin",du:"bist","er/sie/es":"ist",wir:"sind",ihr:"seid","sie/Sie":"sind"}},
{inf:"haben",es:"tener",type:"irregular",conj:{ich:"habe",du:"hast","er/sie/es":"hat",wir:"haben",ihr:"habt","sie/Sie":"haben"}},
{inf:"werden",es:"llegar a ser",type:"irregular",conj:{ich:"werde",du:"wirst","er/sie/es":"wird",wir:"werden",ihr:"werdet","sie/Sie":"werden"}},
{inf:"können",es:"poder",type:"modal",conj:{ich:"kann",du:"kannst","er/sie/es":"kann",wir:"können",ihr:"könnt","sie/Sie":"können"}},
{inf:"müssen",es:"deber/tener que",type:"modal",conj:{ich:"muss",du:"musst","er/sie/es":"muss",wir:"müssen",ihr:"müsst","sie/Sie":"müssen"}},
{inf:"wollen",es:"querer",type:"modal",conj:{ich:"will",du:"willst","er/sie/es":"will",wir:"wollen",ihr:"wollt","sie/Sie":"wollen"}},
{inf:"dürfen",es:"tener permiso",type:"modal",conj:{ich:"darf",du:"darfst","er/sie/es":"darf",wir:"dürfen",ihr:"dürft","sie/Sie":"dürfen"}},
{inf:"sollen",es:"deber (consejo)",type:"modal",conj:{ich:"soll",du:"sollst","er/sie/es":"soll",wir:"sollen",ihr:"sollt","sie/Sie":"sollen"}},
{inf:"mögen",es:"gustar",type:"modal",conj:{ich:"mag",du:"magst","er/sie/es":"mag",wir:"mögen",ihr:"mögt","sie/Sie":"mögen"}},
{inf:"möchten",es:"quisiera",type:"modal",conj:{ich:"möchte",du:"möchtest","er/sie/es":"möchte",wir:"möchten",ihr:"möchtet","sie/Sie":"möchten"}},
{inf:"machen",es:"hacer",type:"regular",conj:{ich:"mache",du:"machst","er/sie/es":"macht",wir:"machen",ihr:"macht","sie/Sie":"machen"}},
{inf:"gehen",es:"ir (a pie)",type:"irregular",conj:{ich:"gehe",du:"gehst","er/sie/es":"geht",wir:"gehen",ihr:"geht","sie/Sie":"gehen"}},
{inf:"kommen",es:"venir",type:"irregular",conj:{ich:"komme",du:"kommst","er/sie/es":"kommt",wir:"kommen",ihr:"kommt","sie/Sie":"kommen"}},
{inf:"sprechen",es:"hablar",type:"stem-change",conj:{ich:"spreche",du:"sprichst","er/sie/es":"spricht",wir:"sprechen",ihr:"sprecht","sie/Sie":"sprechen"}},
{inf:"essen",es:"comer",type:"stem-change",conj:{ich:"esse",du:"isst","er/sie/es":"isst",wir:"essen",ihr:"esst","sie/Sie":"essen"}},
{inf:"trinken",es:"beber",type:"regular",conj:{ich:"trinke",du:"trinkst","er/sie/es":"trinkt",wir:"trinken",ihr:"trinkt","sie/Sie":"trinken"}},
{inf:"schlafen",es:"dormir",type:"stem-change",conj:{ich:"schlafe",du:"schläfst","er/sie/es":"schläft",wir:"schlafen",ihr:"schlaft","sie/Sie":"schlafen"}},
{inf:"fahren",es:"ir (en vehículo)",type:"stem-change",conj:{ich:"fahre",du:"fährst","er/sie/es":"fährt",wir:"fahren",ihr:"fahrt","sie/Sie":"fahren"}},
{inf:"lesen",es:"leer",type:"stem-change",conj:{ich:"lese",du:"liest","er/sie/es":"liest",wir:"lesen",ihr:"lest","sie/Sie":"lesen"}},
{inf:"sehen",es:"ver",type:"stem-change",conj:{ich:"sehe",du:"siehst","er/sie/es":"sieht",wir:"sehen",ihr:"seht","sie/Sie":"sehen"}},
{inf:"nehmen",es:"tomar/coger",type:"stem-change",conj:{ich:"nehme",du:"nimmst","er/sie/es":"nimmt",wir:"nehmen",ihr:"nehmt","sie/Sie":"nehmen"}},
{inf:"geben",es:"dar",type:"stem-change",conj:{ich:"gebe",du:"gibst","er/sie/es":"gibt",wir:"geben",ihr:"gebt","sie/Sie":"geben"}},
{inf:"wissen",es:"saber",type:"irregular",conj:{ich:"weiß",du:"weißt","er/sie/es":"weiß",wir:"wissen",ihr:"wisst","sie/Sie":"wissen"}},
{inf:"arbeiten",es:"trabajar",type:"regular",conj:{ich:"arbeite",du:"arbeitest","er/sie/es":"arbeitet",wir:"arbeiten",ihr:"arbeitet","sie/Sie":"arbeiten"}},
{inf:"spielen",es:"jugar",type:"regular",conj:{ich:"spiele",du:"spielst","er/sie/es":"spielt",wir:"spielen",ihr:"spielt","sie/Sie":"spielen"}},
{inf:"lernen",es:"aprender",type:"regular",conj:{ich:"lerne",du:"lernst","er/sie/es":"lernt",wir:"lernen",ihr:"lernt","sie/Sie":"lernen"}},
{inf:"kaufen",es:"comprar",type:"regular",conj:{ich:"kaufe",du:"kaufst","er/sie/es":"kauft",wir:"kaufen",ihr:"kauft","sie/Sie":"kaufen"}},
{inf:"wohnen",es:"vivir/residir",type:"regular",conj:{ich:"wohne",du:"wohnst","er/sie/es":"wohnt",wir:"wohnen",ihr:"wohnt","sie/Sie":"wohnen"}},
{inf:"heißen",es:"llamarse",type:"regular",conj:{ich:"heiße",du:"heißt","er/sie/es":"heißt",wir:"heißen",ihr:"heißt","sie/Sie":"heißen"}},
{inf:"finden",es:"encontrar/opinar",type:"regular",conj:{ich:"finde",du:"findest","er/sie/es":"findet",wir:"finden",ihr:"findet","sie/Sie":"finden"}},
{inf:"helfen",es:"ayudar",type:"stem-change",conj:{ich:"helfe",du:"hilfst","er/sie/es":"hilft",wir:"helfen",ihr:"helft","sie/Sie":"helfen"}},
{inf:"laufen",es:"correr/caminar",type:"stem-change",conj:{ich:"laufe",du:"läufst","er/sie/es":"läuft",wir:"laufen",ihr:"lauft","sie/Sie":"laufen"}},
{inf:"tragen",es:"llevar/cargar",type:"stem-change",conj:{ich:"trage",du:"trägst","er/sie/es":"trägt",wir:"tragen",ihr:"tragt","sie/Sie":"tragen"}},
{inf:"waschen",es:"lavar",type:"stem-change",conj:{ich:"wasche",du:"wäschst","er/sie/es":"wäscht",wir:"waschen",ihr:"wascht","sie/Sie":"waschen"}},
];

const PLURALS_A1 = [
{singular:"der Hund",plural:"die Hunde",es:"perro(s)",rule:"-e",emoji:"🐕"},
{singular:"die Katze",plural:"die Katzen",es:"gato(s)",rule:"-n",emoji:"🐱"},
{singular:"der Tisch",plural:"die Tische",es:"mesa(s)",rule:"-e",emoji:"🪑"},
{singular:"das Kind",plural:"die Kinder",es:"niño(s)",rule:"-er",emoji:"👶"},
{singular:"das Buch",plural:"die Bücher",es:"libro(s)",rule:"-̈er",emoji:"📚"},
{singular:"die Frau",plural:"die Frauen",es:"mujer(es)",rule:"-en",emoji:"👩"},
{singular:"der Mann",plural:"die Männer",es:"hombre(s)",rule:"-̈er",emoji:"👨"},
{singular:"das Haus",plural:"die Häuser",es:"casa(s)",rule:"-̈er",emoji:"🏠"},
{singular:"der Stuhl",plural:"die Stühle",es:"silla(s)",rule:"-̈e",emoji:"🪑"},
{singular:"die Blume",plural:"die Blumen",es:"flor(es)",rule:"-n",emoji:"🌸"},
{singular:"der Bruder",plural:"die Brüder",es:"hermano(s)",rule:"-̈",emoji:"👦"},
{singular:"die Schwester",plural:"die Schwestern",es:"hermana(s)",rule:"-n",emoji:"👧"},
{singular:"die Mutter",plural:"die Mütter",es:"madre(s)",rule:"-̈",emoji:"👩"},
{singular:"der Vater",plural:"die Väter",es:"padre(s)",rule:"-̈",emoji:"👨"},
{singular:"das Auto",plural:"die Autos",es:"coche(s)",rule:"-s",emoji:"🚗"},
{singular:"der Tag",plural:"die Tage",es:"día(s)",rule:"-e",emoji:"📅"},
{singular:"die Nacht",plural:"die Nächte",es:"noche(s)",rule:"-̈e",emoji:"🌙"},
{singular:"das Ei",plural:"die Eier",es:"huevo(s)",rule:"-er",emoji:"🥚"},
{singular:"der Apfel",plural:"die Äpfel",es:"manzana(s)",rule:"-̈",emoji:"🍎"},
{singular:"die Lampe",plural:"die Lampen",es:"lámpara(s)",rule:"-n",emoji:"💡"},
{singular:"das Mädchen",plural:"die Mädchen",es:"chica(s)",rule:"-",emoji:"👧"},
{singular:"der Lehrer",plural:"die Lehrer",es:"profesor(es)",rule:"-",emoji:"👨‍🏫"},
{singular:"die Schule",plural:"die Schulen",es:"escuela(s)",rule:"-n",emoji:"🏫"},
{singular:"der Freund",plural:"die Freunde",es:"amigo(s)",rule:"-e",emoji:"🤝"},
{singular:"die Tasche",plural:"die Taschen",es:"bolsa(s)",rule:"-n",emoji:"👜"},
{singular:"das Zimmer",plural:"die Zimmer",es:"habitación(es)",rule:"-",emoji:"🚪"},
{singular:"der Schuh",plural:"die Schuhe",es:"zapato(s)",rule:"-e",emoji:"👟"},
{singular:"die Hand",plural:"die Hände",es:"mano(s)",rule:"-̈e",emoji:"✋"},
{singular:"das Glas",plural:"die Gläser",es:"vaso(s)",rule:"-̈er",emoji:"🥛"},
{singular:"der Zug",plural:"die Züge",es:"tren(es)",rule:"-̈e",emoji:"🚂"},
{singular:"die Stadt",plural:"die Städte",es:"ciudad(es)",rule:"-̈e",emoji:"🏙️"},
{singular:"das Foto",plural:"die Fotos",es:"foto(s)",rule:"-s",emoji:"📷"},
{singular:"der Arzt",plural:"die Ärzte",es:"médico(s)",rule:"-̈e",emoji:"👨‍⚕️"},
{singular:"die Zeitung",plural:"die Zeitungen",es:"periódico(s)",rule:"-en",emoji:"📰"},
{singular:"das Hemd",plural:"die Hemden",es:"camisa(s)",rule:"-en",emoji:"👔"},
];

const CASES_A1 = [
{sentence:"Ich sehe ___ Hund.",opts:["den","dem","der","das"],correct:0,case:"Akkusativ",es:"Veo al perro.",tip:"sehen + Akkusativ. Masculino: der → <b>den</b>"},
{sentence:"___ Mann ist groß.",opts:["Der","Den","Dem","Das"],correct:0,case:"Nominativ",es:"El hombre es alto.",tip:"Sujeto = Nominativ. Masculino: <b>der</b>"},
{sentence:"Ich gebe ___ Frau das Buch.",opts:["der","die","den","dem"],correct:0,case:"Dativ",es:"Le doy el libro a la mujer.",tip:"geben + Dativ (a quién). Femenino: die → <b>der</b>"},
{sentence:"Er kauft ___ Auto.",opts:["ein","einen","einem","einer"],correct:0,case:"Akkusativ",es:"Él compra un coche.",tip:"kaufen + Akkusativ. Neutro: ein → <b>ein</b> (no cambia)"},
{sentence:"Ich trinke ___ Kaffee.",opts:["einen","ein","einem","einer"],correct:0,case:"Akkusativ",es:"Bebo un café.",tip:"trinken + Akkusativ. Masculino: ein → <b>einen</b>"},
{sentence:"___ Kind spielt im Garten.",opts:["Das","Den","Dem","Der"],correct:0,case:"Nominativ",es:"El niño juega en el jardín.",tip:"Sujeto = Nominativ. Neutro: <b>das</b>"},
{sentence:"Ich helfe ___ Kind.",opts:["dem","das","den","der"],correct:0,case:"Dativ",es:"Ayudo al niño.",tip:"helfen + Dativ. Neutro: das → <b>dem</b>"},
{sentence:"Er hat ___ Schwester.",opts:["eine","einen","einem","einer"],correct:0,case:"Akkusativ",es:"Él tiene una hermana.",tip:"haben + Akkusativ. Femenino: eine → <b>eine</b> (no cambia)"},
{sentence:"Wir danken ___ Lehrer.",opts:["dem","den","der","das"],correct:0,case:"Dativ",es:"Agradecemos al profesor.",tip:"danken + Dativ. Masculino: der → <b>dem</b>"},
{sentence:"Ich brauche ___ Stift.",opts:["einen","ein","einem","einer"],correct:0,case:"Akkusativ",es:"Necesito un bolígrafo.",tip:"brauchen + Akkusativ. Masculino: ein → <b>einen</b>"},
{sentence:"___ Kinder spielen draußen.",opts:["Die","Den","Dem","Das"],correct:0,case:"Nominativ",es:"Los niños juegan afuera.",tip:"Sujeto plural = Nominativ. Plural siempre: <b>die</b>"},
{sentence:"Ich schreibe ___ Freund einen Brief.",opts:["dem","den","der","das"],correct:0,case:"Dativ",es:"Le escribo una carta al amigo.",tip:"schreiben + Dativ (a quién). Masculino: der → <b>dem</b>"},
{sentence:"Sie liest ___ Buch.",opts:["das","dem","den","der"],correct:0,case:"Akkusativ",es:"Ella lee el libro.",tip:"lesen + Akkusativ. Neutro: das → <b>das</b> (no cambia)"},
{sentence:"Ich komme mit ___ Bus.",opts:["dem","den","der","das"],correct:0,case:"Dativ",es:"Vengo en autobús.",tip:"mit + Dativ (siempre). Masculino: der → <b>dem</b>"},
{sentence:"Das Buch ist für ___ Mutter.",opts:["die","der","dem","den"],correct:0,case:"Akkusativ",es:"El libro es para la madre.",tip:"für + Akkusativ (siempre). Femenino: die → <b>die</b> (no cambia)"},
{sentence:"Er fährt zu ___ Schule.",opts:["der","die","dem","den"],correct:0,case:"Dativ",es:"Él va a la escuela.",tip:"zu + Dativ (siempre). Femenino: die → <b>der</b>"},
{sentence:"Wir wohnen in ___ Stadt.",opts:["der","die","dem","den"],correct:0,case:"Dativ",es:"Vivimos en la ciudad.",tip:"in + Dativ (ubicación/wo?). Femenino: die → <b>der</b>"},
{sentence:"Ich gehe in ___ Park.",opts:["den","dem","der","das"],correct:0,case:"Akkusativ",es:"Voy al parque.",tip:"in + Akkusativ (dirección/wohin?). Masculino: der → <b>den</b>"},
{sentence:"Das Geschenk ist von ___ Vater.",opts:["dem","den","der","das"],correct:0,case:"Dativ",es:"El regalo es del padre.",tip:"von + Dativ (siempre). Masculino: der → <b>dem</b>"},
{sentence:"Ich suche ___ Schlüssel.",opts:["den","dem","der","das"],correct:0,case:"Akkusativ",es:"Busco la llave.",tip:"suchen + Akkusativ. Masculino: der → <b>den</b>"},
{sentence:"Er antwortet ___ Lehrerin.",opts:["der","die","dem","den"],correct:0,case:"Dativ",es:"Él le responde a la profesora.",tip:"antworten + Dativ. Femenino: die → <b>der</b>"},
{sentence:"Sie geht ohne ___ Regenschirm.",opts:["den","dem","der","das"],correct:0,case:"Akkusativ",es:"Ella va sin el paraguas.",tip:"ohne + Akkusativ (siempre). Masculino: der → <b>den</b>"},
{sentence:"Ich fahre mit ___ Fahrrad.",opts:["dem","das","den","der"],correct:0,case:"Dativ",es:"Voy en bicicleta.",tip:"mit + Dativ (siempre). Neutro: das → <b>dem</b>"},
{sentence:"Nach ___ Essen gehen wir spazieren.",opts:["dem","das","den","der"],correct:0,case:"Dativ",es:"Después de comer paseamos.",tip:"nach + Dativ (siempre). Neutro: das → <b>dem</b>"},
{sentence:"___ Katze schläft auf dem Sofa.",opts:["Die","Der","Dem","Den"],correct:0,case:"Nominativ",es:"La gata duerme en el sofá.",tip:"Sujeto = Nominativ. Femenino: <b>die</b>"},
];

const LISTENING_A1 = [
{id:"listen_bahnhof",title:"Am Bahnhof",desc:"En la estación de tren",
dialogue:[
{speaker:"A",de:"Entschuldigung, wann fährt der nächste Zug nach München?"},
{speaker:"B",de:"Der nächste Zug fährt um vierzehn Uhr dreißig."},
{speaker:"A",de:"Von welchem Gleis?"},
{speaker:"B",de:"Von Gleis sieben."},
{speaker:"A",de:"Wie viel kostet eine Fahrkarte?"},
{speaker:"B",de:"Einfach oder hin und zurück?"},
{speaker:"A",de:"Hin und zurück, bitte."},
{speaker:"B",de:"Das macht neunundvierzig Euro."},
],quiz:[
{q:"¿A qué hora sale el tren?",opts:["13:30","14:30","15:30","14:00"],correct:1},
{q:"¿A qué ciudad va el tren?",opts:["Berlin","Hamburg","München","Frankfurt"],correct:2},
{q:"¿De qué Gleis sale?",opts:["Gleis 5","Gleis 7","Gleis 9","Gleis 3"],correct:1},
{q:"¿Cuánto cuesta hin und zurück?",opts:["39 €","49 €","59 €","29 €"],correct:1},
]},
{id:"listen_arzt",title:"Beim Arzt",desc:"En el médico",
dialogue:[
{speaker:"A",de:"Guten Tag, was fehlt Ihnen?"},
{speaker:"B",de:"Ich habe seit drei Tagen Kopfschmerzen und Fieber."},
{speaker:"A",de:"Haben Sie auch Halsschmerzen?"},
{speaker:"B",de:"Ja, und ich bin sehr müde."},
{speaker:"A",de:"Ich verschreibe Ihnen Tabletten. Nehmen Sie dreimal am Tag eine Tablette."},
{speaker:"B",de:"Wie lange soll ich die Tabletten nehmen?"},
{speaker:"A",de:"Fünf Tage. Und trinken Sie viel Wasser."},
{speaker:"B",de:"Danke, Herr Doktor."},
],quiz:[
{q:"¿Desde cuándo tiene el paciente Kopfschmerzen?",opts:["Seit einem Tag","Seit drei Tagen","Seit einer Woche","Seit gestern"],correct:1},
{q:"¿Qué más tiene además de Kopfschmerzen?",opts:["Nur Fieber","Fieber und Halsschmerzen","Bauchschmerzen","Rückenschmerzen"],correct:1},
{q:"¿Cuántas veces al día debe tomar las Tabletten?",opts:["Einmal","Zweimal","Dreimal","Viermal"],correct:2},
{q:"¿Cuántos Tage debe tomar la medicina?",opts:["Drei","Fünf","Sieben","Zehn"],correct:1},
]},
{id:"listen_supermarkt",title:"Im Supermarkt",desc:"En el supermercado",
dialogue:[
{speaker:"A",de:"Entschuldigung, wo finde ich die Milch?"},
{speaker:"B",de:"Die Milch steht im Gang drei, neben dem Käse."},
{speaker:"A",de:"Und haben Sie auch Vollkornbrot?"},
{speaker:"B",de:"Ja, das Brot finden Sie in Gang eins."},
{speaker:"A",de:"Was kostet dieses Brot?"},
{speaker:"B",de:"Zwei Euro fünfzig."},
{speaker:"A",de:"Gut, ich nehme das. Kann ich mit Karte bezahlen?"},
{speaker:"B",de:"Ja, natürlich. Die Kasse ist dort vorne."},
],quiz:[
{q:"¿En qué Gang está la Milch?",opts:["Gang 1","Gang 2","Gang 3","Gang 4"],correct:2},
{q:"¿Qué está neben la Milch?",opts:["Das Brot","Der Käse","Die Butter","Der Saft"],correct:1},
{q:"¿Cuánto kostet das Brot?",opts:["1,50 €","2,00 €","2,50 €","3,00 €"],correct:2},
{q:"¿Cómo quiere bezahlen?",opts:["Bar (efectivo)","Mit Karte","Mit dem Handy","Mit Gutschein"],correct:1},
]},
{id:"listen_anrufbeantworter",title:"Anrufbeantworter",desc:"Mensajes en el contestador",
dialogue:[
{speaker:"📞",de:"Hallo, hier ist die Praxis von Doktor Meier. Wir haben Montag bis Freitag von acht bis zwölf Uhr und von vierzehn bis achtzehn Uhr geöffnet. Am Mittwochnachmittag ist die Praxis geschlossen. Bitte rufen Sie morgen wieder an oder hinterlassen Sie eine Nachricht nach dem Ton."},
],quiz:[
{q:"¿De quién es el contestador?",opts:["Ein Restaurant","Eine Arztpraxis","Eine Schule","Ein Büro"],correct:1},
{q:"¿Cuándo está abierto por la mañana?",opts:["7-11 Uhr","8-12 Uhr","9-13 Uhr","8-11 Uhr"],correct:1},
{q:"¿Cuándo está cerrado?",opts:["Montagnachmittag","Dienstagnachmittag","Mittwochnachmittag","Freitagnachmittag"],correct:2},
]},
{id:"listen_wegbeschreibung",title:"Wegbeschreibung",desc:"Cómo llegar a un lugar",
dialogue:[
{speaker:"A",de:"Entschuldigung, wie komme ich zum Rathaus?"},
{speaker:"B",de:"Gehen Sie hier geradeaus bis zur Ampel."},
{speaker:"A",de:"Und dann?"},
{speaker:"B",de:"An der Ampel biegen Sie links ab. Dann gehen Sie etwa zweihundert Meter geradeaus."},
{speaker:"A",de:"Ist es weit?"},
{speaker:"B",de:"Nein, nur fünf Minuten zu Fuß. Das Rathaus ist auf der rechten Seite, neben der Kirche."},
{speaker:"A",de:"Vielen Dank!"},
],quiz:[
{q:"¿A dónde quiere ir?",opts:["Zum Bahnhof","Zur Schule","Zum Rathaus","Zum Krankenhaus"],correct:2},
{q:"¿Qué debe hacer an der Ampel?",opts:["Rechts abbiegen","Links abbiegen","Geradeaus gehen","Zurückgehen"],correct:1},
{q:"¿Wie weit ist es?",opts:["2 Minuten","5 Minuten","10 Minuten","15 Minuten"],correct:1},
{q:"¿Neben welchem Gebäude ist das Rathaus?",opts:["Neben dem Supermarkt","Neben der Schule","Neben der Kirche","Neben dem Bahnhof"],correct:2},
]},
{id:"listen_wetter",title:"Wetterbericht",desc:"El pronóstico del tiempo",
dialogue:[
{speaker:"📻",de:"Guten Morgen! Hier ist der Wetterbericht für heute, Samstag, den fünfzehnten März. Am Vormittag ist es bewölkt bei zehn Grad. Am Nachmittag kommt die Sonne und es wird wärmer, bis fünfzehn Grad. Am Abend regnet es, vergessen Sie Ihren Regenschirm nicht! Am Sonntag wird es wieder schön mit zwanzig Grad."},
],quiz:[
{q:"¿Qué día es?",opts:["Freitag","Samstag","Sonntag","Montag"],correct:1},
{q:"¿Cómo es el Vormittag?",opts:["Sonnig","Bewölkt","Regnerisch","Schnee"],correct:1},
{q:"¿Cuántos Grad am Nachmittag?",opts:["10 Grad","15 Grad","20 Grad","25 Grad"],correct:1},
{q:"¿Qué pasa am Abend?",opts:["Es schneit","Es regnet","Es ist sonnig","Es ist kalt"],correct:1},
]},
{id:"listen_telefon",title:"Telefonanruf",desc:"Llamada para pedir cita",
dialogue:[
{speaker:"A",de:"Praxis Doktor Schmidt, guten Tag."},
{speaker:"B",de:"Guten Tag, mein Name ist Müller. Ich möchte einen Termin machen."},
{speaker:"A",de:"Was fehlt Ihnen?"},
{speaker:"B",de:"Ich habe seit zwei Tagen Zahnschmerzen."},
{speaker:"A",de:"Können Sie morgen um neun Uhr kommen?"},
{speaker:"B",de:"Morgen kann ich leider nicht. Geht es auch am Donnerstag?"},
{speaker:"A",de:"Am Donnerstag habe ich um elf Uhr einen Termin frei."},
{speaker:"B",de:"Das passt. Vielen Dank!"},
],quiz:[
{q:"¿Qué tipo de Arzt es Dr. Schmidt?",opts:["Augenarzt","Zahnarzt","Hausarzt","Kinderarzt"],correct:1},
{q:"¿Desde cuándo hat Herr Müller Schmerzen?",opts:["Seit gestern","Seit zwei Tagen","Seit einer Woche","Seit einem Monat"],correct:1},
{q:"¿Kann er morgen kommen?",opts:["Ja","Nein","Vielleicht","Er weiß nicht"],correct:1},
{q:"¿Wann ist der Termin?",opts:["Mittwoch 9 Uhr","Donnerstag 9 Uhr","Donnerstag 11 Uhr","Freitag 11 Uhr"],correct:2},
]},
];

const WRITING_A1 = [
{id:"write_email_friend",title:"Email an einen Freund",desc:"Escribe un email informal a un amigo",
scenario:"Tu amigo Thomas te ha invitado a su fiesta de cumpleaños el sábado. Escribe un email corto (~30 palabras):",
hints:["Agradece la invitación","Di que vas a ir","Pregunta qué puedes llevar"],
keywords:["danke","einladung","komme","gern","samstag","mitbringen","party","geburtstag","feier"],
example:"Lieber Thomas, vielen Dank für die Einladung! Ich komme gern am Samstag zu deiner Geburtstagsfeier. Soll ich etwas mitbringen? Viele Grüße, [Name]"},
{id:"write_email_sick",title:"Krankmeldung",desc:"Avisa que estás enfermo y no puedes ir al curso",
scenario:"Estás enfermo/a y no puedes ir a tu curso de alemán hoy. Escribe un email a tu profesora Frau Müller (~30 palabras):",
hints:["Saluda formalmente","Di que estás enfermo/a","Pide disculpas por no asistir"],
keywords:["frau","müller","krank","leider","heute","kurs","kommen","entschuldigung","morgen"],
example:"Sehr geehrte Frau Müller, leider bin ich heute krank und kann nicht zum Kurs kommen. Ich hoffe, dass ich morgen wieder da bin. Mit freundlichen Grüßen, [Name]"},
{id:"write_formular",title:"Anmeldeformular",desc:"Rellena un formulario de inscripción",
scenario:"Estás inscribiéndote en un curso de alemán. Completa los datos:",
fields:[
{label:"Vorname",placeholder:"Tu nombre..."},
{label:"Nachname / Familienname",placeholder:"Tu apellido..."},
{label:"Geburtsdatum",placeholder:"TT.MM.JJJJ"},
{label:"Adresse",placeholder:"Calle y número..."},
{label:"Postleitzahl (PLZ)",placeholder:"Código postal..."},
{label:"Telefonnummer",placeholder:"Número de teléfono..."},
]},
];